#!/bin/sh -ex
ORIGINAL_GIT="https://github.com"
MIRROR_GIT="https://:@gitlab.cern.ch:8443"
REPOS="cms-sw/cmssw cms-sw/cmsdist cms-sw/pkgtools cms-sw/cmssw-config cms-sw/SCRAM"
if [ "X$1" != "X" ] ; then
  if [ $(git ls-remote -h "${MIRROR_GIT}/$1" | grep 'refs/heads/' | wc -l) -eq 0 ] ; then
    echo "WARNING: There is no gitlab mirror available for $1"
    exit 0
  fi
  REPOS=$(echo $REPOS | tr ' ' '\n' | sed 's|:.*$||' | grep "$1" || true)
fi

let INDEX=0
for item in $REPOS; do
  let INDEX=$INDEX+1
  REPO=`echo $item | sed 's|:.*||'`
  MIRROR_REPO=`echo $item | sed 's|.*:||'`
  if [ "$MIRROR_REPO" = "" ] ; then MIRROR_REPO=$REPO ; fi
  echo "REPOSITORY=${ORIGINAL_GIT}/${REPO}.git"   > mirror-repo-$INDEX
  echo "MIRROR=${MIRROR_GIT}/${MIRROR_REPO}.git" >> mirror-repo-$INDEX
done

