#!/usr/bin/env python
from sys import argv, exit
from os import environ
from urllib2 import Request, urlopen
from urllib import quote_plus
from commands import getstatusoutput

repo = argv[1]
e, o = getstatusoutput('git ls-remote -h "https://:@gitlab.cern.ch:8443/%s" 2>&1 | grep "refs/heads/" | wc -l' % repo)
if o=='0':
  print "Mirror repository not found:", repo
  exit(0)

TOKEN_FILE="/data/secrets/cmsbuild-gitlab-secret"
if 'GITLAB_SECRET_TOKEN' in environ: TOKEN_FILE=environ['GITLAB_SECRET_TOKEN']
url='https://gitlab.cern.ch/api/v4/projects/%s/mirror/pull' % quote_plus(repo)
headers= {"PRIVATE-TOKEN": open(TOKEN_FILE).read().strip()}
request = Request(url, headers=headers)
request.get_method = lambda: "POST"
response = urlopen(request)
print response.read()

