#!/bin/sh -ex
# Updates a branch by doing the following:
# - switch to the target branch
# - Merge the source branch but keep anything on the development branch
#   in case of conflicts.
# - Update the target branch. 
function updateBranch()
{
  SOURCE_BRANCH=$1
  TARGET_BRANCH=$2
  git clean -fdx
  git reset --hard origin/$TARGET_BRANCH
  git clean -fdx
  git merge --no-ff -X ours origin/$SOURCE_BRANCH
  git commit --amend -m 'Merge $SOURCE_BRANCH into $TARGET_BRANCH.'
  if [ "X`git diff --name-only HEAD origin/$TARGET_BRANCH | tail -1`" != "X" ]; then
    git push origin HEAD:$TARGET_BRANCH
  fi
}

# Update CMSSW
# Clone once
cd $WORKSPACE
rm -rf cmssw
if [ ! -d cmssw ]; then
  git clone -b CMSSW_7_0_X git@github.com:cms-sw/cmssw
fi

cd cmssw

# Make sure we push with our correct name and address 
# in the case our user does not have an home directory,
# e.g. under mesos.
if [ X$HOME = X ]; then
  git config user.email 'cmsbuild@cern.ch'
  git config user.name "CMS Build"
fi

git fetch origin

# CMSSW_7_1_X for the moment is based on CMSSW_7_0_X
updateBranch CMSSW_7_1_X CMSSW_7_1_DEVEL_X
updateBranch CMSSW_7_1_X CMSSW_7_1_CLANG_X

# SLHC branch is based on top of the associated release branch.
updateBranch CMSSW_6_2_X CMSSW_6_2_X_SLHC

# CMSSW_7_2_X for the moment is based on CMSSW_7_1_X
updateBranch CMSSW_7_2_X CMSSW_7_2_ROOT6_X
updateBranch CMSSW_7_2_X CMSSW_7_2_GEANT10_X
updateBranch CMSSW_7_2_X CMSSW_7_2_DEVEL_X
updateBranch CMSSW_7_2_X CMSSW_7_2_CLANG_X
updateBranch CMSSW_7_2_X CMSSW_7_2_THREADED_X

# CMSSW_7_3_X special branches
updateBranch CMSSW_7_3_X CMSSW_7_3_ROOT6_X
updateBranch CMSSW_7_3_X CMSSW_7_3_GEANT10_X
updateBranch CMSSW_7_3_X CMSSW_7_3_THREADED_X
updateBranch CMSSW_7_3_X CMSSW_7_3_CLANG_X
updateBranch CMSSW_7_3_X CMSSW_7_3_DEVEL_X

# CMSSW_7_4_X
updateBranch CMSSW_7_4_X CMSSW_7_4_DEVEL_X
updateBranch CMSSW_7_4_X CMSSW_7_4_THREADED_X
updateBranch CMSSW_7_4_X CMSSW_7_4_ROOT6_X
updateBranch CMSSW_7_4_X CMSSW_7_4_GEANT10_X
updateBranch CMSSW_7_4_X CMSSW_7_4_CLANG_X

# Update CMSDIST
cd $WORKSPACE
if [ ! -d cmsdist ]; then
  git clone -b IB/CMSSW_7_0_X/stable git@github.com:cms-sw/cmsdist
fi

cd cmsdist
# Make sure we push with our correct name and address 
# in the case our user does not have an home directory,
# e.g. under mesos.
if [ X$HOME = X ]; then
  git config user.email 'cmsbuild@cern.ch'
  git config user.name "CMS Build"
fi
git fetch

# CMSSW_6_2_X
updateBranch IB/CMSSW_6_2_X/stable IB/CMSSW_6_2_X/devel-gcc472

# CMSSW_7_0_X
# devel
updateBranch IB/CMSSW_7_0_X/stable IB/CMSSW_7_0_X/devel

# CMSSW_7_1_X
updateBranch IB/CMSSW_7_0_X/stable IB/CMSSW_7_1_X/stable
updateBranch IB/CMSSW_7_1_X/stable IB/CMSSW_7_1_X/jemalloc341
updateBranch IB/CMSSW_7_1_X/stable IB/CMSSW_7_1_X/jemalloc350
updateBranch IB/CMSSW_7_1_X/stable IB/CMSSW_7_1_X/gcc490
updateBranch IB/CMSSW_7_1_X/stable IB/CMSSW_7_1_X/devel
updateBranch IB/CMSSW_7_1_X/stable IB/CMSSW_7_1_X/next
updateBranch IB/CMSSW_7_1_X/stable IB/CMSSW_7_1_X/root5
updateBranch IB/CMSSW_7_1_X/stable IB/CMSSW_7_1_X/debug
updateBranch IB/CMSSW_7_1_X/stable IB/CMSSW_7_1_X/debug-gcc491

# CMSSW_7_2_X
updateBranch IB/CMSSW_7_2_X/stable IB/CMSSW_7_2_X/geant10
updateBranch IB/CMSSW_7_2_X/stable IB/CMSSW_7_2_X/gcc491
updateBranch IB/CMSSW_7_2_X/stable IB/CMSSW_7_2_X/next

# CMSSW_7_3_X
updateBranch IB/CMSSW_7_3_X/stable IB/CMSSW_7_3_X/gcc491
updateBranch IB/CMSSW_7_3_X/stable IB/CMSSW_7_3_X/root6
updateBranch IB/CMSSW_7_3_X/stable IB/CMSSW_7_3_X/asan
updateBranch IB/CMSSW_7_3_X/stable IB/CMSSW_7_3_X/geant10
updateBranch IB/CMSSW_7_3_X/stable IB/CMSSW_7_3_X/next
updateBranch IB/CMSSW_7_3_X/stable IB/CMSSW_7_3_X/debug

# CMSSW_7_4_X
# Since the production arch for 74X is gcc491, IB/CMSSW_7_3_X/491
# merges into IB/CMSSW_7_4_X/stable Then it merges into the
# other cmsdist branches for 74X as usual
updateBranch IB/CMSSW_7_4_X/stable IB/CMSSW_7_4_X/gcc481
updateBranch IB/CMSSW_7_4_X/stable IB/CMSSW_7_4_X/next
updateBranch IB/CMSSW_7_4_X/stable IB/CMSSW_7_4_X/root6
updateBranch IB/CMSSW_7_4_X/stable IB/CMSSW_7_4_X/geant10
updateBranch IB/CMSSW_7_4_X/stable IB/CMSSW_7_4_X/debug
