#!/bin/bash -ex
CMS_BOT_DIR=$(dirname $0)
case $CMS_BOT_DIR in /*) ;; *) CMS_BOT_DIR=$(pwd)/${CMS_BOT_DIR} ;; esac

REF_CMSSW_VERSION=$1
eval `scram run -sh`
mkdir -p $LOCALRT/run/Images
cd $LOCALRT/run

OLD_MB_DIR="material-budget-ref/${REF_CMSSW_VERSION}/${SCRAM_ARCH}"
NEW_MB_DIR="material-budget/${CMSSW_VERSION}/${SCRAM_ARCH}"
PR_TESTS=NO
if [ $(echo $REF_CMSSW_VERSION | grep '^[1-9][0-9]*' | wc -l) -gt 0 ] ; then
  NEW_MB_DIR="pull-request-integration/PR-${REF_CMSSW_VERSION}/material-budget"
  OLD_MB_DIR="material-budget/${CMSSW_VERSION}/${SCRAM_ARCH}"
  PR_TESTS=YES
fi

#Remove biglib path from LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$(echo $LD_LIBRARY_PATH | tr ':' '\n' | grep -v /biglib/$SCRAM_ARCH | tr '\n' ':' | sed 's|:$||')

source $CMS_BOT_DIR/jenkins-artifacts
get_jenkins_artifacts $NEW_MB_DIR/matbdg_Tracker.root $LOCALRT/run/matbdg_Tracker_new.root || exit 1
get_jenkins_artifacts $OLD_MB_DIR/matbdg_Tracker.root $LOCALRT/run/matbdg_Tracker_old.root || exit 1
cp $CMSSW_RELEASE_BASE/src/Validation/Geometry/test/TrackerMaterialBudgetComparison.C .
root -l -b -q 'TrackerMaterialBudgetComparison.C("Tracker")' > $LOCALRT/run/compare.log 2>&1
rm -f $LOCALRT/run/matbdg_Tracker*.root $LOCALRT/run/TrackerMaterialBudgetComparison.C
if [ "$PR_TESTS" = "NO" ] ; then
  ln -sf ../../../../material-budget-ref/${REF_CMSSW_VERSION}/${SCRAM_ARCH} ref
  echo ${REF_CMSSW_VERSION} > $LOCALRT/run/cmssw-ref-release
else
  ln -sf ../../../../material-budget/${CMSSW_VERSION}/${SCRAM_ARCH} ref
  echo ${CMSSW_VERSION} > $LOCALRT/run/cmssw-ref-release
fi
send_jenkins_artifacts $LOCALRT/run ${NEW_MB_DIR}/comparison || exit 1

