#!/usr/bin/env python
from github import Github, GithubException
from os.path import expanduser
from optparse import OptionParser
from datetime import datetime
from sys import exit
import re
from socket import setdefaulttimeout
setdefaulttimeout(120)

if __name__ == "__main__":
  parser = OptionParser(usage="%prog -b|--branch <branch> -d|--date <YYYY-MM-DD-HH00> -t|--tag <tag> [-n|--dry-run]")
  parser.add_option("-r", "--repository",  dest="repo",  help="Github repository e.g. cms-sw/cmssw", type=str, default='cms-sw/cmssw')
  parser.add_option("-m", "--match",       dest="match", help="Regexp to match tags e.g. CMSSW_8_0_X", type=str, default='CMSSW_.+')
  opts, args = parser.parse_args()

  gh = Github(login_or_token=open(expanduser("~/.github-token")).read().strip())
  rate_limit = gh.get_rate_limit().rate
  print 'API Rate Limit'
  print 'Limit: ', rate_limit.limit
  print 'Remaining: ', rate_limit.remaining
  print 'Reset time (GMT): ', rate_limit.reset

  repo =  gh.get_repo(opts.repo)
  tags  = repo.get_releases()
  tagRe = re.compile ('^'+opts.match+'.*$')
  for t in tags:
    if tagRe.match(t.name):
      print t.name

