#!/usr/bin/env python

from argparse import ArgumentParser
from sys import exit
from os.path import expanduser
from github import Github

if __name__ == "__main__":
  parser = ArgumentParser()
  parser.add_argument("number", nargs=1)
  args = parser.parse_args()

  prId = int(args.number[0])
  gh = Github(login_or_token=open(expanduser("~/.github-token")).read().strip())
  try:
    pr = gh.get_organization("cms-sw").get_repo("cmssw").get_pull(prId)
  except Exception as ex:
    print "Could not find pull request. Maybe this is an issue"
    print ex
    exit(1)

  print pr.base.ref
