#!/bin/sh -ex

[ -f ib-weeks ] || exit 1

WEEK_NO="nweek-${CMS_WEEK_NUM}"
WEEK_FOUND=`grep "^$WEEK_NO\$" ib-weeks | wc -l`

if [ "X$WEEK_FOUND" = "X0" ] ; then
  rm -rf dummybuild
  mkdir dummybuild
  eval `cat $(dirname $0)/config.map | grep -v 'DISABLED=1' | grep 'RELEASE_BRANCH=master' | grep  'PROD_ARCH=1;'`
  PKGS=""
  pushd dummybuild
    git clone -b $CMSDIST_TAG           git://github.com/cms-sw/cmsdist.git CMSDIST   || git clone -b $CMSDIST_TAG https://:@git.cern.ch/kerberos/CMSDIST.git CMSDIST
    git clone -b $PKGTOOLS_TAG          git://github.com/cms-sw/pkgtools.git PKGTOOLS || git clone -b $PKGTOOLS_TAG             https://:@git.cern.ch/kerberos/PKGTOOLS.git PKGTOOLS
    echo -e "### RPM cms dummy `date +%s`\n## NOCOMPILER\nSource: none\n%prep\n%build\n%install\n" > CMSDIST/dummy.spec
    PKGTOOLS/cmsBuild --debug --repository cms --architecture $SCRAM_ARCH --work-dir w build dummy SCRAMV1 crab
    PKGTOOLS/cmsBuild --debug --repository cms --upload-tmp-repository $CMS_REPOSITORY --architecture $SCRAM_ARCH --work-dir w upload dummy SCRAMV1 crab
    PKGS=$(ls -d w/${SCRAM_ARCH}/cms/crab/*/etc w/${SCRAM_ARCH}/lcg/SCRAMV1/*/etc | sed "s|^w/${SCRAM_ARCH}/||;s|/etc$||;s|/|+|g")
  popd
  rm -rf dummybuild
  echo "$WEEK_NO" >> ib-weeks
  git commit -m "Added new ib-week $WEEK_NO" ib-weeks
  git pull --rebase
  git push origin
  echo "ARCHITECTURE=${SCRAM_ARCH}" > cvmfs-reset-week 
  echo "REPOSITORY=cms.${CMS_REPOSITORY}" >> cvmfs-reset-week
  echo "RELEASE_FORMAT=" >> cvmfs-reset-week
  echo "CMSDIST_HASH=" >> cvmfs-reset-week
  echo "INSTALL_PACKAGES=${PKGS}" >> cvmfs-reset-week
fi
