#!/bin/bash -ex
ARTIFACTS_USER=$(whoami)
case ${ARTIFACTS_USER} in
  cmsbld|cvcmsib) ARTIFACTS_USER="cmsbuild" ;;
esac
ARTIFACTS_MACHINE=${ARTIFACTS_USER}@cmssdt02.cern.ch
ARTIFACT_BASE_DIR=/data/sdt/SDT/jenkins-artifacts
SSH_OPTS="-q -o ConnectTimeout=60 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ServerAliveInterval=60"

function has_jenkins_artifacts ()
{
  local SRC=$1
  local TYPE=$2
  [ "X$TYPE" = "X" ] && TYPE="-e"
  for i in 1 2 3 4 5 6 7 8 9 ;  do
    RES=$(ssh $SSH_OPTS ${ARTIFACTS_MACHINE} "echo JA_RUN${i}=CONN && test ${TYPE} ${ARTIFACT_BASE_DIR}/${SRC} || echo JA_RUN${i}=FAIL" | grep "^JA_RUN${i}=" | wc -l)
    if [ $RES -eq 1 ] ; then
      echo "JA_STATUS=OK"
      return 0
    elif [ $RES -eq 2 ] ; then
      echo "JA_STATUS=ERROR"
      return 1
    else
      sleep 60
    fi
  done
  echo "JA_STATUS=ERROR"
  return 1
}

function send_jenkins_artifacts ()
{
  local SRC=$1
  local DES=$2
  local IS_DIR=$(test -d $SRC && echo "/")
  local DES_DIR=$DES
  if [ "X$IS_DIR" = "X" ] ; then DES_DIR=$(dirname $DES) ; fi
  for i in 1 2 3 4 5 6 7 8 9 ;  do
    ( ssh $SSH_OPTS ${ARTIFACTS_MACHINE} mkdir -p ${ARTIFACT_BASE_DIR}/${DES_DIR} && \
      rsync -az -e "ssh $SSH_OPTS" ${SRC}${IS_DIR} ${ARTIFACTS_MACHINE}:${ARTIFACT_BASE_DIR}/${DES_DIR}${IS_DIR} && echo "JA_STATUS=OK") && return
    sleep 60
  done
  echo "JA_STATUS=ERROR"
  return 1
}

function get_jenkins_artifacts ()
{
  local SRC=$1
  local DES=$2
  if [ "X$3" = "X" -a -e /cvmfs/cms-ib.cern.ch/jenkins-artifacts/$SRC ] ; then
    if [ -d /cvmfs/cms-ib.cern.ch/jenkins-artifacts/$SRC ] ; then
      local XSRC=$(echo $SRC | sed 's|/*$||')
      local XDES=$(echo $DES | sed 's|/*$||')
      mkdir -p $XDES && rm -rf $XDES
      ln -s /cvmfs/cms-ib.cern.ch/jenkins-artifacts/$XSRC $XDES
    else
      mkdir -p $(dirname $DES)
      cp -f /cvmfs/cms-ib.cern.ch/jenkins-artifacts/$SRC $DES
    fi
    echo "JA_STATUS=OK"
    return
  fi
  case $SRC in
    */) mkdir -p $DES ; DES="${DES}/";;
    * ) mkdir -p $(dirname $DES) ;;
  esac
  has_jenkins_artifacts $1 || return 1
  for i in 1 2 3 4 5 6 7 8 9 ;  do
    rsync -az -e "ssh $SSH_OPTS" ${ARTIFACTS_MACHINE}:${ARTIFACT_BASE_DIR}/${SRC} ${DES} && echo "JA_STATUS=OK" && return
    sleep 60
  done
  echo "JA_STATUS=ERROR"
  return 1
}

