#!/bin/sh -ex

kinit -R
WORKSPACE=${WORKSPACE-$PWD}
#MIRROR=/afs/.cern.ch/cms/git-cmssw-mirror
MIRROR=/data/git-mirrors
CERN_GIT=https://:@gitlab.cern.ch:8443/cms-sw
GITHUB=https://github.com/cms-sw
REPOS="cmssw:cmssw cmsdist:cmsdist pkgtools:pkgtools cmssw-config:cmssw-config SCRAM:SCRAM"

git config --global http.postBuffer 209715200
ERR=0
mkdir -p ${MIRROR}
mkdir -p ${WORKSPACE}/repos
for item in $REPOS; do
  cd ${WORKSPACE}/repos
  GH_REPO=`echo $item | sed 's|:.*||'`
  rm -rf ${GH_REPO}.git
  git clone --bare ${GITHUB}/${GH_REPO}.git || (ERR=1 && continue)
  rsync -a --delete ${GH_REPO}.git/ ${MIRROR}/${GH_REPO}.git/
done
cd ${WORKSPACE}
rm -rf ${WORKSPACE}/repos

case $MIRROR in
  /afs/* )
    /afs/cern.ch/cms/sdt/internal/requestHandler/requestGitMirrorSync.py
    du -sh /afs/.cern.ch/cms/git-cmssw-mirror
    ;;
esac

for item in $REPOS; do
  GH_REPO=`echo $item | sed 's|:.*||'`
  CERN_REPO=`echo $item | sed 's|.*:||'`
  [ -d ${MIRROR}/${GH_REPO}.git ] || continue
  cd ${MIRROR}/${GH_REPO}.git
  git push -f --mirror ${CERN_GIT}/${CERN_REPO}.git || (ERR=1 && continue)
done

exit $ERR

