#!/bin/sh -ex

kinit -R
WORKSPACE=${WORKSPACE-$PWD}
MIRROR=/data/git-mirrors
CERN_GIT=https://:@gitlab.cern.ch:8443
GITHUB=https://github.com
REPOS="cms-sw/cmssw cms-sw/cmsdist cms-sw/pkgtools cms-sw/cmssw-config cms-sw/SCRAM"
if [ "X$1" != "X" ] ; then
  if [ $(git ls-remote -h ${CERN_GIT}/$1 | grep 'refs/heads/' | wc -l) -eq 0 ] ; then
    echo "WARNING: There is no gitlab mirror available for $REPO"
    exit 0
  fi
  REPOS=$(echo $REPOS | tr ' ' '\n' | sed 's|:.*$||' | grep "$1" || true)
fi

git config --global http.postBuffer 209715200
ERR=0
for item in $REPOS; do
  GH_REPO=`echo $item | sed 's|:.*||'`
  repo_owner=$(dirname $GH_REPO)
  mkdir -p ${WORKSPACE}/repos/${repo_owner}
  mkdir -p ${MIRROR}/${repo_owner}
  rm -rf ${WORKSPACE}/repos/${GH_REPO}.git
  cd ${WORKSPACE}/repos/${repo_owner}
  git clone --bare ${GITHUB}/${GH_REPO}.git || (ERR=1 && continue)
  rsync -a --delete ${GH_REPO}.git/ ${MIRROR}/${GH_REPO}.git/
done
cd ${WORKSPACE}
rm -rf ${WORKSPACE}/repos
ls -d ${MIRROR}/*
ls -d ${MIRROR}/*/*
exit 0

case $MIRROR in
  /afs/* )
    /afs/cern.ch/cms/sdt/internal/requestHandler/requestGitMirrorSync.py
    du -sh /afs/.cern.ch/cms/git-cmssw-mirror
    ;;
esac

for item in $REPOS; do
  GH_REPO=`echo $item | sed 's|:.*||'`
  CERN_REPO=`echo $item | sed 's|.*:||'`
  if [ "$CERN_REPO" = "" ] ; then CERN_REPO=$GH_REPO ; fi 
  [ -d ${MIRROR}/${GH_REPO}.git ] || continue
  cd ${MIRROR}/${GH_REPO}.git
  git push -f --mirror ${CERN_GIT}/${CERN_REPO}.git || (ERR=1 && continue)
done

exit $ERR

