#!/bin/sh -ex

kinit -R
WORKSPACE=${WORKSPACE-$PWD}
ORIGINAL_GIT=https://github.com
MIRROR_GIT=https://:@gitlab.cern.ch:8443
REPOS="cms-sw/cmssw cms-sw/cmsdist cms-sw/pkgtools cms-sw/cmssw-config cms-sw/SCRAM"
if [ "X$1" != "X" ] ; then
  if [ $(git ls-remote -h ${MIRROR_GIT}/$1 | grep 'refs/heads/' | wc -l) -eq 0 ] ; then
    echo "WARNING: There is no gitlab mirror available for $REPO"
    exit 0
  fi
  REPOS=$(echo $REPOS | tr ' ' '\n' | sed 's|:.*$||' | grep "$1" || true)
fi

git config --global http.postBuffer 209715200
ERR=0
for item in $REPOS; do
  REPO=`echo $item | sed 's|:.*||'`
  MIRROR_REPO=`echo $item | sed 's|.*:||'`
  if [ "$MIRROR_REPO" = "" ] ; then MIRROR_REPO=$REPO ; fi
  rm -rf ${WORKSPACE}/mirror-git-repo
  if git clone --bare ${ORIGINAL_GIT}/${REPO}.git ${WORKSPACE}/mirror-git-repo ; then
    pushd ${WORKSPACE}/mirror-git-repo
      echo git push -f --mirror ${MIRROR_GIT}/${MIRROR_REPO}.git || ERR=1
    popd
  else
    ERR=1
  fi
done
rm -rf ${WORKSPACE}/mirror-git-repo
exit $ERR

