#!/bin/sh -ex
CMS_BOT_DIR=$(dirname $0)
case $CMS_BOT_DIR in /*) ;; *) CMS_BOT_DIR=$(pwd)/${CMS_BOT_DIR} ;; esac
ARCHITECTURE_FILTER=${ARCHITECTURE_FILTER-.*}

cd $WORKSPACE

# The pull request number is $1
PULL_REQUEST=$1

# Use helper to get PR branch
RELEASE_QUEUE=`$CMS_BOT_DIR/get-pr-branch $PULL_REQUEST`
CONFIG_MAP_FILE="$CMS_BOT_DIR/config.map"

PROP_FILE=properties-pr
if [ "X$CMSDIST_PR" != "X" ] ; then 
  PROP_FILE=cmsdist-properties-pr
fi
rm -f $WORKSPACE/pr_test_ok
COMP_QUEUE=$(echo $RELEASE_QUEUE | sed 's|^\(CMSSW_[0-9]*_[0-9]*\)_.*|\1_X|')
COMP_ARCH=$(grep "RELEASE_QUEUE=$COMP_QUEUE;" $CONFIG_MAP_FILE | grep -v "DISABLED=" | grep "PROD_ARCH=1;" | tr ';' '\n' | grep "SCRAM_ARCH=" | sed 's|SCRAM_ARCH=||')

MLINES=`grep "=$RELEASE_QUEUE;" $CONFIG_MAP_FILE | grep -v DISABLED= | grep "SCRAM_ARCH=$ARCHITECTURE_FILTER;"`
MLC=$(echo $MLINES | tr ';' '\n' | grep SCRAM_ARCH= | wc -l)
if [ $MLC -gt 1 ] ; then
  MLINES=$(grep "=$RELEASE_QUEUE;" $CONFIG_MAP_FILE | grep -v DISABLED= |  grep "SCRAM_ARCH=$COMP_ARCH;" | grep "PROD_ARCH=1")
  MLC=$(echo $MLINES | tr ';' '\n' | grep SCRAM_ARCH= | wc -l)
fi
if [ $MLC -eq 1 ] ; then
    eval $MLINES
    if [ "X$CMSDIST_PR" != "X" ] ; then SCRAM_ARCH="" ; fi
    touch $WORKSPACE/pr_test_ok
    OUTPUT_FILE=${PROP_FILE}-${PULL_REQUEST}-${SCRAM_ARCH}.txt
    echo PULL_REQUEST=${PULL_REQUEST} > $OUTPUT_FILE
    echo ARCHITECTURE=${SCRAM_ARCH} >> $OUTPUT_FILE
    if [ "X$RELEASE_FORMAT" = X ] ; then
      echo RELEASE_FORMAT=${RELEASE_QUEUE} >> $OUTPUT_FILE
    else
      echo RELEASE_FORMAT=${RELEASE_FORMAT} >> $OUTPUT_FILE
    fi
    echo DO_TESTS=${DO_TESTS} >> $OUTPUT_FILE
    echo DO_SHORT_MATRIX=${DO_SHORT_MATRIX} >> $OUTPUT_FILE
    echo DO_STATIC_CHECKS=${DO_STATIC_CHECKS} >> $OUTPUT_FILE
    echo DO_DUPLICATE_CHECKS=${DO_DUPLICATE_CHECKS} >> $OUTPUT_FILE
    echo MATRIX_EXTRAS=${MATRIX_EXTRAS} >> $OUTPUT_FILE
    echo ADDITIONAL_PULL_REQUESTS=${ADDITIONAL_PULL_REQUESTS} >> $OUTPUT_FILE
    echo WORKFLOWS_FOR_VALGRIND_TEST=${WORKFLOWS_FOR_VALGRIND_TEST} >> $OUTPUT_FILE
    echo AUTO_POST_MESSAGE=${AUTO_POST_MESSAGE} >> $OUTPUT_FILE
    echo RUN_CONFIG_VIEWER=${RUN_CONFIG_VIEWER} >> $OUTPUT_FILE
    echo USE_DAS_CACHE=${USE_DAS_CACHE} >> $OUTPUT_FILE
    echo USE_JOB_REPORTS=${USE_JOB_REPORTS} >> $OUTPUT_FILE
    echo BRANCH_NAME=${BRANCH_NAME} >> $OUTPUT_FILE
    echo APPLY_FIREWORKS_RULE=${APPLY_FIREWORKS_RULE} >> $OUTPUT_FILE
    echo RUN_IGPROF=${RUN_IGPROF} >> $OUTPUT_FILE
    echo CMSDIST_PR=${CMSDIST_PR} >> $OUTPUT_FILE
    echo FULL_TOOLCONF=true >> $OUTPUT_FILE
    echo PYTHONDONTWRITEBYTECODE=1 >> $OUTPUT_FILE
    echo COMPARISON_ARCH=${COMP_ARCH} >> $OUTPUT_FILE
fi

if [ ! -f $WORKSPACE/pr_test_ok ] ; then
  $CMS_BOT_DIR/report-pull-request-results RELEASE_NOT_FOUND --pr $PULL_REQUEST --pr-job-id ${BUILD_NUMBER}
fi

