#!/usr/bin/env python                                                                                                                                                                                                  
from github import Github
from os.path import expanduser
from optparse import OptionParser
from categories import CMSSW_CATEGORIES, CMSSW_L2
from datetime import datetime, timedelta
import re

if __name__ == "__main__":
  parser = OptionParser(usage="%prog <since-n-seconds>")
  opts, args = parser.parse_args()
  if not len(args):
    parser.error("Please specify the number of seconds since you want updates")

  since = datetime.utcnow() - timedelta(seconds=int(args[0]))
  gh = Github(login_or_token=open(expanduser("~/.github-token")).read().strip())
  issues = gh.get_organization("cms-sw").get_repo("cmssw").get_issues(state="open", sort="updated", since=since)
  print " ".join([str(x.number) for x in issues])
