#!/bin/sh -ex
CMSSW_X_Y_Z=$1
ARCHITECTURE=$2

RPM_NAME=cmssw
case $CMSSW_X_Y_Z in
   *patch*) RPM_NAME=cmssw-patch ;;
esac

BASERELEASE=$(echo $CMSSW_X_Y_Z | sed -e 's/_[a-zA-Z0-9]*patch[0-9].*//')
while ! fs lq /afs/.cern.ch/cms/$ARCHITECTURE/cms/cmssw/$BASERELEASE | grep -E '[2-9]000000'; do
  echo Waiting for volume ; sleep 10
done

source /afs/cern.ch/cms/cmsset_default.sh
/afs/.cern.ch/cms/common/cmspkg -a $ARCHITECTURE update
/afs/.cern.ch/cms/common/cmspkg -a $ARCHITECTURE -f upgrade
/afs/.cern.ch/cms/common/cmspkg -a $ARCHITECTURE install -y $(/afs/.cern.ch/cms/common/cmspkg -a $ARCHITECTURE search $CMSSW_X_Y_Z | sed -e 's|[ ].*||' | grep -e "^cms[+]$RPM_NAME[+]$CMSSW_X_Y_Z\$")
/afs/.cern.ch/cms/common/cmspkg -a $ARCHITECTURE -f clean || true
touch /afs/.cern.ch/cms/$ARCHITECTURE/tmp/$CMSSW_X_Y_Z
echo 'ALL_OK'

