#!/bin/sh -ex
CMS_BOT_DIR=$(dirname $0)
case $CMS_BOT_DIR in /*) ;; *) CMS_BOT_DIR=$(pwd)/${CMS_BOT_DIR} ;; esac
WORKFLOWS=$1
PROFILES=$2
EVENTS=$3
if [ "X$EVENTS" = "X" ] ; then EVENTS=1000; fi
for prof in ${PROFILES} ; do
  mkdir -p $WORKSPACE/igprof/${prof}
  cd $WORKSPACE/igprof/${prof}
  runTheMatrix.py $WORKFLOWS --ibeos --command "-n $EVENTS --profile $prof" 2>&1 | tee runTheMatrix.log
  for f in $(find . -name '*.gz' -type f) ; do
    echo "processing file $f"
    OUTFILE=${f//.gz/.sql3}
    echo $OUTFILE
    ERR=0
    ( igprof-analyse -d -c $f --sqlite > $f.sql ) || ERR=1
    ${CMS_BOT_DIR}/fix-igprof-sql.py $f.sql | sqlite3 "$OUTFILE" > $f.log || ERR=1

    OUTFILE="$(basename $f).txt"
    echo $OUTFILE
    if [ "$prof" = "pp" ]; then
        ( igprof-analyse -v -d -g $f > "RES_CPU_${OUTFILE}" ) || ERR=1
        if [[ $OUTFILE == "step3"*"_EndOfJob.gz"  && $WORKFLOWS != "-i all -l 13"* ]];then
            export IGREP=RES_CPU_${OUTFILE}.txt
            export IGSORT=sorted_RES_CPU_step3.txt
            awk -v module=doEvent 'BEGIN { total = 0; } { if(substr(\$0,0,1)=="-"){good = 0;}; if(good&&length(\$0)>0){print \$0; total += \$3;}; if(substr(\$0,0,1)=="["&&index(\$0,module)!=0) {good = 1;} } END { print "Total: "total } ' \${IGREP} | sort -n -r -k1 | awk '{ if(index(\$0,"Total: ")!=0){total=\$0;} else{print \$0;} } END { print total; }' > \${IGSORT} 2>&1
        fi
    fi
    if [ "$prof" = "mp" ]; then
        ( igprof-analyse -v -d -g -r MEM_LIVE $f > "RES_MEM_${OUTFILE}") || ERR=1
    fi

    if [ $ERR -gt 0 ] ; then
      cat $f.log
    fi
  done
done
