#!/bin/bash -ex

cmsRun $CMSSW_RELEASE_BASE/src/Validation/Geometry/python/single_neutrino_cfg.py >$LOCALRT/single_neutrino_cfg.log 2>&1
#Remove big plugin paths
export LD_LIBRARY_PATH=$(echo $LD_LIBRARY_PATH | tr ':' '\n' | grep -v /biglib/$SCRAM_ARCH | tr '\n' ':' | sed 's|:$||')
cmsRun $CMSSW_RELEASE_BASE/src/Validation/Geometry/test/runP_Tracker_cfg.py >$LOCALRT/runP_Tracker_cfg.log 2>&1
mkdir Images

if [[ $(ls ${CMSSW_RELEASE_BASE}/src/Validation/Geometry/test/ | grep MaterialBudget | wc -l) -gt 0 ]]  ; then
  cp $CMSSW_RELEASE_BASE/src/Validation/Geometry/test/MaterialBudget* .
  if [ -e MaterialBudget.C ] ; then
    root -b -q 'MaterialBudget.C("Tracker")' || true
  elif [ -e MaterialBudget.py ] ; then
    python MaterialBudget.py -s -d Tracker || true
  else
    echo "MaterialBudget script is neither .C nor .py, exit"
    exit 1
  fi
else
  echo "Script ${CMSSW_RELEASE_BASE}/src/Validation/Geometry/test/MaterialBudget does not exist, exit"
  exit 1
fi
