#!/bin/sh -ex
BASE_URL=cmsbuild@vocms12.cern.ch:/data/sdt/SDT/jenkins-artifacts/ib-baseline-tests/$RELEASE_FORMAT/$ARCHITECTURE/matrix-results/
PULL_REQUEST_BASE_URL=cmsbuild@vocms12.cern.ch:/data/sdt/SDT/jenkins-artifacts/pull-request-integration/PR-$PULL_REQUEST_NUMBER/$PULL_REQUEST_JOB_ID/runTheMatrix-results/

WF_NAME_4_22='4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC/DQM_V0001_R000160960__Global__CMSSW_X_Y_Z__RECO.root'
WF_NAME_4_53='4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODreHLT+HARVESTDreHLT/DQM_V0001_R000194533__Global__CMSSW_X_Y_Z__RECO.root'
WF_NAME_5_1='5.1_TTbar+TTbarFS+HARVESTFS/DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO.root'
WF_NAME_8_0='8.0_BeamHalo+BeamHalo+DIGICOS+RECOCOS+ALCABH+HARVESTCOS/DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO.root'
WF_NAME_25_0='25.0_TTbar+TTbar+DIGI+RECO+HARVEST+ALCATT/DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO.root'
WF_NAME_401_0='401.0_TTbarNewMix+TTbarFSPU2+HARVESTFS/DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO.root'
WF_NAME_1000_0='1000.0_RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT/DQM_V0001_R000165121__Global__CMSSW_X_Y_Z__RECO.root'
#WF_NAME_101_0='101.0_SingleElectronE120EHCAL+SingleElectronE120EHCAL/DQM_V0001_R000165121__Express__PCLTest__ALCAPROMPT.root'
WF_NAME_1306_0='1306.0_SingleMuPt1_UP15+SingleMuPt1_UP15+DIGIUP15+RECOUP15+HARVESTUP15/DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO.root'
#WF_NAME_1003_0='1003.0_RunMinBias2012A+RunMinBias2012A+RECODDQM+HARVESTDDQM/DQM_V0001_R000191226__Global__CMSSW_X_Y_Z__RECO.root'
#WF_NAME_1001_0='1001.0_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD/DQM_V0001_R000165121__Express__PCLTest__ALCAPROMPT.root'

WORKFLOWS_TO_COMPARE=$WF_NAME_4_22,$WF_NAME_4_53,$WF_NAME_5_1,$WF_NAME_8_0,$WF_NAME_25_0,$WF_NAME_401_0,$WF_NAME_1000_0,$WF_NAME_1306_0


export SCRAM_ARCH=$ARCHITECTURE
scram project $RELEASE_FORMAT
cd $RELEASE_FORMAT
eval `scram run -sh`
git cms-addpkg Utilities/RelMon
cd ..

mkdir $WORKSPACE/results
cd $WORKSPACE/results

rsync cmsbuild@vocms12.cern.ch:/data/sdt/SDT/jenkins-artifacts/pull-request-integration/PR-$PULL_REQUEST_NUMBER/$PULL_REQUEST_JOB_ID/summary.html $WORKSPACE/results/summary.html

# --------------------------------------------------------------------------
# Download the Files
# --------------------------------------------------------------------------
mkdir $WORKSPACE/results/files
cd $WORKSPACE/results/files

for WF in ${WORKFLOWS_TO_COMPARE//,/ }; do
  
  echo '#######################################'
  echo 'downloading:'
  echo $WF

  WF_BASE_URL=$BASE_URL$WF
  WF_PR_URL=$PULL_REQUEST_BASE_URL$WF
  WF_FILE=$(basename $WF)

  WF_DIR=`echo $WF | cut -d "/" -f1`

  mkdir $WORKSPACE/results/files/$WF_DIR
  cd $WORKSPACE/results/files/$WF_DIR

    rsync $WF_BASE_URL $WORKSPACE/results/files/$WF_DIR/$RELEASE_FORMAT-$WF_FILE
    rsync $WF_PR_URL $WORKSPACE/results/files/$WF_DIR/$PULL_REQUEST_NUMBER-$WF_FILE

  cd ..

done

cd ..

echo 'Finished downloading files:'

pwd
ls -R

# --------------------------------------------------------------------------
# Default Comparison
# --------------------------------------------------------------------------

mkdir $WORKSPACE/results/default-comparison

for WF in ${WORKFLOWS_TO_COMPARE//,/ }; do 

  WF_BASE_URL=$BASE_URL$WF
  WF_PR_URL=$PULL_REQUEST_BASE_URL$WF
  WF_FILE=$(basename $WF)
  WF_DIR=`echo $WF | cut -d "/" -f1`

  WF_NUMBER=`echo $WF | cut -d'_' -f1`

  #create the output dir
  OUTPUT_DIR=$WORKSPACE/results/default-comparison/$WF_DIR
  mkdir -p $OUTPUT_DIR

  #requires checking out Utilities/RelMon from the release. 
  compare_using_files.py $WORKSPACE/results/files/$WF_DIR/$RELEASE_FORMAT-$WF_FILE $WORKSPACE/results/files/$WF_DIR/$PULL_REQUEST_NUMBER-$WF_FILE -o $OUTPUT_DIR --metas " $RELEASE_FORMAT @@@ $RELEASE_FORMAT + $PULL_REQUEST_NUMBER " --use_black_file -C -R -p --no_successes -s b2b --standalone || true

  cd $OUTPUT_DIR
    cp RelMonSummary.html index.html
    find . -name "*" | xargs sh -c "sed -i -s 's/..\/RelMonSummary.html/RelMonSummary.html/g' || true"
  cd ..

  echo 'compare_using_files.py '$WORKSPACE'/results/files/'$WF_DIR'/'$RELEASE_FORMAT'-'$WF_FILE' '$WORKSPACE'/results/files/'$WF_DIR'/'$PULL_REQUEST_NUMBER'-'$WF_FILE' -o '$OUTPUT_DIR' --metas " '$RELEASE_FORMAT' @@@ '$RELEASE_FORMAT' + '$PULL_REQUEST_NUMBER' " --use_black_file -C -R -p --no_successes -s b2b --standalone || true ' > $WORKSPACE/results/default-comparison/command-$WF_NUMBER

done

echo 'Finished with default comparison'


# ----------------------------------------------------------------------------
# Alternative Comparison
# ----------------------------------------------------------------------------

ALT_COMP_DIR=$WORKSPACE/results/alternative-comparison
mkdir -p $ALT_COMP_DIR
cp $WORKSPACE/cms-bot/comparisons/compareValHists.C $ALT_COMP_DIR
cp $WORKSPACE/cms-bot/comparisons/makeDiff.sh $ALT_COMP_DIR


for WF in ${WORKFLOWS_TO_COMPARE//,/ }; do 

  WF_BASE_URL=$BASE_URL$WF
  WF_PR_URL=$PULL_REQUEST_BASE_URL$WF
  WF_FILE=$(basename $WF)
  WF_DIR=`echo $WF | cut -d "/" -f1`

  WF_NUMBER=`echo $WF | cut -d'_' -f1`

  BASE_FILE=$WORKSPACE/results/files/$WF_DIR/$RELEASE_FORMAT-$WF_FILE
  COMP_FILE=$WORKSPACE/results/files/$WF_DIR/$PULL_REQUEST_NUMBER-$WF_FILE

  cd $ALT_COMP_DIR
    source $ALT_COMP_DIR/makeDiff.sh $BASE_FILE $COMP_FILE $WF_NUMBER-result.ps 0 1 || true
  cd ..
  
  echo 'source '$ALT_COMP_DIR'/makeDiff.sh '$BASE_FILE' '$COMP_FILE' '$WF_NUMBER'-result 0 1 || true' > $ALT_COMP_DIR/command-$WF_NUMBER

done

echo 'Finished with alternative comparison:'



# --------------------------------------------------------------------------
# JR-Comparison
# --------------------------------------------------------------------------

JR_COMP_DIR=$WORKSPACE/results/JR-comparison

mkdir -p $JR_COMP_DIR

cp $WORKSPACE/cms-bot/comparisons/validateJR.sh $JR_COMP_DIR
cp $WORKSPACE/cms-bot/comparisons/validate.C $JR_COMP_DIR
cp $WORKSPACE/cms-bot/comparisons/matrix_70X.txt $JR_COMP_DIR

mkdir -p $HOME/tools
cp $WORKSPACE/cms-bot/comparisons/validate.C $HOME/tools


#Download the baseline files
rsync -r cmsbuild@vocms12.cern.ch:/data/sdt/SDT/jenkins-artifacts/ib-baseline-tests/$RELEASE_FORMAT/$ARCHITECTURE/matrix-results/ $JR_COMP_DIR/$RELEASE_FORMAT

#Download the files for the pr
rsync -r cmsbuild@vocms12.cern.ch:/data/sdt/SDT/jenkins-artifacts/pull-request-integration/PR-$PULL_REQUEST_NUMBER/$PULL_REQUEST_JOB_ID/runTheMatrix-results/ $JR_COMP_DIR/PR-$PULL_REQUEST_NUMBER

cd $JR_COMP_DIR
  source $JR_COMP_DIR/validateJR.sh $JR_COMP_DIR/PR-$PULL_REQUEST_NUMBER $JR_COMP_DIR/$RELEASE_FORMAT OldVSNew matrix_70X.txt 2>&1 | tee -a $JR_COMP_DIR/validateJR.log
cd ..

echo  'source '$JR_COMP_DIR'/validateJR.sh '$JR_COMP_DIR'/PR-'$PULL_REQUEST_NUMBER' '$JR_COMP_DIR'/'$RELEASE_FORMAT' OldVSNew matrix_70X.txt 2>&1 | tee -a '$JR_COMP_DIR'/validateJR.log' > $JR_COMP_DIR/command

echo 'Finished with JR comparison:'



sed -i "s/PARAM_BASELINE_COMPARISON/https:\/\/cmssdt.cern.ch\/SDT\/jenkins-artifacts\/baseLineComparisons\/$RELEASE_FORMAT+$PULL_REQUEST_NUMBER\/$BUILD_NUMBER\//g" $WORKSPACE/results/summary.html
sed -i "s/Still running.../See comparison results/g" $WORKSPACE/results/summary.html

