#!/bin/sh -ex
WORKFLOWS=$1
PROFILES=$2
for prof in ${PROFILES} ; do
  mkdir -p $WORKSPACE/igprof/${prof}
  cd $WORKSPACE/igprof/${prof}
  runTheMatrix.py $WORKFLOWS --command "--profile $prof" > runTheMatrix.log
  find . -type d | while read d; do
    echo "processing dir $d"
    for f in $d/*.gz ; do
      echo "processing file $f"
      OUTFILE=${f//.gz/.sql3}
      echo $OUTFILE
      igprof-analyse -d -c $f --sqlite | sqlite3 $OUTFILE > igprof-analyse.log
    done
  done
done
