#!/bin/bash -ex
CMS_BOT_DIR=$(dirname $0)
case $CMS_BOT_DIR in /*) ;; *) CMS_BOT_DIR=$(pwd)/${CMS_BOT_DIR} ;; esac

PULL_REQUEST=$1
export USER_CODE_CHECKS=$2
BUILD_NUMBER=$3
DRY_RUN=$4
if [ "$BUILD_NUMBER" = "" ] ; then BUILD_NUMBER=$(date +%s); fi
NUM_PROC=$(getconf _NPROCESSORS_ONLN)
case $(hostname) in lxplus* ) let NUM_PROC=$NUM_PROC/2 ;; esac
if [ $NUM_PROC = "0" ] ; then NUM_PROC=1; fi
cd $CMSSW_BASE
git clone --depth 1 git@github.com:cms-sw/cmssw-config
mv config/SCRAM config/SCRAM.orig
mv cmssw-config/SCRAM config/SCRAM
git cms-checkout-topic -u ${PULL_REQUEST} 2>&1 | tee cms-checkout-topic.log
scram build -j $NUM_PROC code-checks   2>&1 | tee code-checks.log
rm -rf ${CMSSW_BASE}/upload
mv ${CMSSW_BASE}/tmp/${SCRAM_ARCH}/code-checks-logs ${CMSSW_BASE}/upload
mv cms-checkout-topic.log ${CMSSW_BASE}/upload/
mv code-checks.log ${CMSSW_BASE}/upload/
cd $CMSSW_BASE/src
git diff > ${CMSSW_BASE}/upload/git-diff.patch

source $CMS_BOT_DIR/jenkins-artifacts
send_jenkins_artifacts ${CMSSW_BASE}/upload pr-code-checks/PR-${PULL_REQUEST}/${BUILD_NUMBER}
RES="+code-checks"
HOW_TO_RUN=""
if [ -s ${CMSSW_BASE}/upload/git-diff.patch ] ; then
  RES="-code-checks"
  HOW_TO_RUN="@N@@N@Code check has found code style and quality issues which could be resolved by applying a patch in https://cmssdt.cern.ch/SDT/jenkins-artifacts/pr-code-checks/PR-${PULL_REQUEST}/${BUILD_NUMBER}/git-diff.patch"
  HOW_TO_RUN="${HOW_TO_RUN}@N@@N@In future, you can run \`scram build code-checks\` to apply code checks"
fi
MSG="${RES}@N@@N@Logs: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pr-code-checks/PR-${PULL_REQUEST}/${BUILD_NUMBER}"
${CMS_BOT_DIR}/comment-gh-pr $DRY_RUN -r cms-sw/cmssw -p $PULL_REQUEST -m "${MSG}${HOW_TO_RUN}"
