#!/bin/sh -ex

# Reset kerberos token every time you run.
aklog
kinit cmsbuild@CERN.CH -k -t ~/private/cmsbuild.keytab

cd "$WORKSPACE"
git clone git@github.com:$CMS_GIT_TOOLS_REPO/cms-git-tools

### this is for triggering the comparison with the baseline
  PULL_REQUEST_NUMBER=$PULL_REQUEST
  PULL_REQUEST_JOB_ID=${BUILD_NUMBER}
### to know at the end of the tests if everything went ok
ALL_OK=true
BUILD_OK=true
UNIT_TESTS_OK=true
RELVALS_OK=true

# Checkout the correct ref
pushd cms-git-tools
 git checkout $CMS_GIT_TOOLS_REF
popd

export PATH=$PWD/cms-git-tools:$PATH
which git-cms-merge-topic
git config --global user.github cmsbuild
export SCRAM_ARCH=$ARCHITECTURE

if [[ $RELEASE_FORMAT != *-* ]]; then
  RELEASE_FORMAT=`scram l -c $RELEASE_FORMAT | tail -1 | awk '{print $2}'`
fi

# creation of results summary file
cp $WORKSPACE/templates/PullRequestSummary.html $WORKSPACE/summary.html
cp $WORKSPACE/templates/js/renderPRTests.js $WORKSPACE/renderPRTests.js
RESULTS_FILE=$WORKSPACE/testsResults.txt
touch $RESULTS_FILE
echo 'PR_NUMBER;'$PULL_REQUEST >> $RESULTS_FILE
echo 'ADDITIONAL_PRS;'$ADDITIONAL_PULL_REQUESTS >> $RESULTS_FILE
echo 'BASE_IB;'$RELEASE_FORMAT >> $RESULTS_FILE
echo 'BUILD_NUMBER;'$BUILD_NUMBER >> $RESULTS_FILE

scram project $RELEASE_FORMAT
cd $RELEASE_FORMAT
eval `scram run -sh`
cd src
git config --replace-all merge.renamelimit 2500

# use the branch name if necesary

if [ "X$BRANCH_NAME" = X ]; then
  git cms-merge-topic -u $PULL_REQUEST
else
  git cms-merge-topic -u $BRANCH_NAME
fi


# this is to test several pull requests at the same time
for PR in ${ADDITIONAL_PULL_REQUESTS//,/ }; do
  echo 'I will add the following pull request to the test'
  echo $PR;
  git cms-merge-topic -u $PR
done

#If Fireworks is the only package involved I only compile and run unit tests
ONLY_FIREWORKS=false
if [ "X$APPLY_FIREWORKS_RULE" = Xtrue ]; then

  ls $WORKSPACE/$RELEASE_FORMAT/src
  NUM_DIRS=$((`(find $WORKSPACE/$RELEASE_FORMAT/src -maxdepth 1 -type d -print | grep -v '.git' | grep -v 'FWCore' | wc -l)`-1))

  if [ "$NUM_DIRS" == 1 ]; then

    if ls | grep 'Fireworks'; then
      ONLY_FIREWORKS=true
      echo 'This pr only involves Fireworks!' 
      echo 'Only compiling and running unit tests'
    fi 

  fi

fi

#get the latest commit and mark it as pending
pushd $WORKSPACE

  wget https://pypi.python.org/packages/source/r/requests/requests-2.3.0.tar.gz#md5=7449ffdc8ec9ac37bbcd286003c80f00
  tar -xvf requests-2.3.0.tar.gz
  mv requests-2.3.0/requests/ requests

popd


pushd $WORKSPACE/$RELEASE_FORMAT/src

  if [ "X$BRANCH_NAME" = X ]; then
    LAST_COMMIT=`git log cms-sw/refs/pull/$PULL_REQUEST/head --pretty="%H" | head -n1` 
  else
    LAST_COMMIT=`git log ${BRANCH_NAME//:/\/} --pretty="%H" | head -n1`
  fi

popd

if [ "X$AUTO_POST_MESSAGE" = Xtrue ]; then
  $WORKSPACE/report-pull-request-results TESTS_RUNNING --pr $PULL_REQUEST_NUMBER -c $LAST_COMMIT --pr-job-id $PULL_REQUEST_JOB_ID
fi

############################################
# Force the run of DQM tests if necessary
############################################

if ls $WORKSPACE/$RELEASE_FORMAT/src/| grep -i -E "dqm.*|HLTriggerOffline|Validation"; then
  echo "I will make sure that DQM tests will be run"
  if ls $WORKSPACE/$RELEASE_FORMAT/src/| grep "DQMServices"; then
    echo “DQMServices is already there”
      if ls $WORKSPACE/$RELEASE_FORMAT/src/DQMServices/| grep "Components"; then
        echo "and DQMServices/Components is there"
      else
        git cms-addpkg DQMServices/Components
      fi
  else
    echo "checking out DQMServices"
    git cms-addpkg DQMServices
  fi
fi


git log --oneline --merges ${CMSSW_VERSION}..
git cms-checkdeps -A -a

if [ "X$AUTO_POST_MESSAGE" = Xtrue ]; then
  $WORKSPACE/report-pull-request-results TESTS_RUNNING --pr $PULL_REQUEST_NUMBER -c $LAST_COMMIT --pr-job-id $PULL_REQUEST_JOB_ID --add-message "Compiling"
fi

scram b -k -j $(getconf _NPROCESSORS_ONLN) 2>&1 | tee -a $WORKSPACE/build.log
echo 'END OF BUILD LOG'
echo '--------------------------------------'

if grep -E "^gmake: .* Error [0-9]" $WORKSPACE/build.log; then
    echo "Errors when building"
    echo 'COMPILATION_RESULTS;ERROR' >> $RESULTS_FILE
    ALL_OK=false
    BUILD_OK=false
else  
    echo "the build had no errors!!"
    echo 'COMPILATION_RESULTS;OK' >> $RESULTS_FILE
fi

#
# Unit tests
#
if [ "X$DO_TESTS" = Xtrue -a "X$BUILD_OK" = Xtrue ]; then
  if [ "X$AUTO_POST_MESSAGE" = Xtrue ]; then
    $WORKSPACE/report-pull-request-results TESTS_RUNNING --pr $PULL_REQUEST_NUMBER -c $LAST_COMMIT --pr-job-id $PULL_REQUEST_JOB_ID --add-message "Running Unit Tests"
  fi  
  echo '--------------------------------------'
  scram b -k -j $(getconf _NPROCESSORS_ONLN)  runtests 2>&1 | tee -a $WORKSPACE/unitTests.log
  echo 'END OF UNIT TESTS'
  echo '--------------------------------------'
  #######################################
  # check if DQM Tests where run
  #######################################
  if ls $WORKSPACE/$RELEASE_FORMAT/src/DQMServices/Components/test/ | grep -v -E "[a-z]+"; then 
    echo "DQM Tests were run!"
    pushd $WORKSPACE/$RELEASE_FORMAT/src/DQMServices/Components/test/
    ls | grep -v -E "[a-z]+" | xargs -I ARG mv ARG DQMTestsResults
    mkdir $WORKSPACE/DQMTestsResults
    cp -r DQMTestsResults $WORKSPACE/DQMTestsResults
    ls $WORKSPACE
    popd

    echo 'DQM_TESTS;OK' >> $RESULTS_FILE
  else

    echo 'DQM_TESTS;NOTRUN' >> $RESULTS_FILE

  fi

  if grep -i "had errors" $WORKSPACE/unitTests.log; then
    echo "Errors in the unit tests"
    echo 'UNIT_TEST_RESULTS;ERROR' >> $RESULTS_FILE
    ALL_OK=false
    UNIT_TESTS_OK=false
  else
    echo 'UNIT_TEST_RESULTS;OK' >> $RESULTS_FILE
  fi


else

  echo 'UNIT_TEST_RESULTS;NOTRUN' >> $RESULTS_FILE
  echo 'DQM_TESTS;NOTRUN' >> $RESULTS_FILE

fi


#
# Static checks
#
if [ "X$DO_STATIC_CHECKS" = Xtrue -a "$ONLY_FIREWORKS" = false ]; then

  if [ "X$AUTO_POST_MESSAGE" = Xtrue ]; then
    $WORKSPACE/report-pull-request-results TESTS_RUNNING --pr $PULL_REQUEST_NUMBER -c $LAST_COMMIT --pr-job-id $PULL_REQUEST_JOB_ID --add-message "Running Static Checks"
  fi   
  echo 'STATIC_CHECKS;OK' >> $RESULTS_FILE
  echo '--------------------------------------'
  
  pushd $WORKSPACE/$RELEASE_FORMAT
  git cms-addpkg Utilities/StaticAnalyzers
  
  mkdir $WORKSPACE/llvm-analysis
  SCRAM_IGNORE_PACKAGES="Fireworks/% Utilities/StaticAnalyzers" USER_LLVM_CHECKERS="-enable-checker threadsafety -enable-checker cms -disable-checker cms.FunctionDumper" scram b -k -j $(getconf _NPROCESSORS_ONLN) checker SCRAM_IGNORE_SUBDIRS=test 2>&1 | tee -a $WORKSPACE/llvm-analysis/runStaticChecks.log
 
  pwd
  
  cp -R $WORKSPACE/$RELEASE_FORMAT/llvm-analysis/*/* $WORKSPACE/llvm-analysis || true
  echo 'END OF STATIC CHECKS'
  echo '--------------------------------------'
  
  popd
    
else

  echo 'STATIC_CHECKS;NOTRUN' >> $RESULTS_FILE

fi

#
# Matrix tests
#

JOB_REPORTS=""
if [ "X$USE_JOB_REPORTS" = Xtrue ]; then
  JOB_REPORTS='--job-reports'
fi

if [ ! "X$MATRIX_EXTRAS" = X ]; then
  MATRIX_EXTRAS="-l `echo $MATRIX_EXTRAS | sed -e 's/[^0-9., ]*//g'`"
fi


if [ "X$DO_SHORT_MATRIX" = Xtrue -a "X$BUILD_OK" = Xtrue -a "$ONLY_FIREWORKS" = false ]; then
  if [ "X$AUTO_POST_MESSAGE" = Xtrue ]; then
    $WORKSPACE/report-pull-request-results TESTS_RUNNING --pr $PULL_REQUEST_NUMBER -c $LAST_COMMIT --pr-job-id $PULL_REQUEST_JOB_ID --add-message "Running RelVals"
  fi
  echo '--------------------------------------'
  mkdir "$WORKSPACE/runTheMatrix-results"
  pushd "$WORKSPACE/runTheMatrix-results"
    
    if [ "X$USE_DAS_CACHE" = Xtrue ]; then
      wget --no-check-certificate https://raw.githubusercontent.com/cms-sw/cmsdist/IB/CMSSW_7_1_X/stable/das-cache.file
    
      case $RELEASE_FORMAT in 
        *THREADED*)
        echo "Threaded!"
        runTheMatrix.py --command '--customise FWCore/Concurrency/dropNonMTSafe.dropNonMTSafe' --das-options="--cache das-cache.file" --job-reports -j $(getconf _NPROCESSORS_ONLN) -s $MATRIX_EXTRAS 2>&1 | tee -a $WORKSPACE/matrixTests.log ;;
       *)runTheMatrix.py ${OVERRIDE_MATRIX_PARAMETERS} --das-options='--cache das-cache.file' $JOB_REPORTS -s -j $(getconf _NPROCESSORS_ONLN) $MATRIX_EXTRAS 2>&1 | tee -a $WORKSPACE/matrixTests.log ;;
       esac

    else

      case $RELEASE_FORMAT in 
        *THREADED*)
        echo "Threaded!"
        runTheMatrix.py --command '--customise FWCore/Concurrency/dropNonMTSafe.dropNonMTSafe' --das-options="--cache das-cache.file" --job-reports -j $(getconf _NPROCESSORS_ONLN) -s $MATRIX_EXTRAS 2>&1 | tee -a $WORKSPACE/matrixTests.log ;;
       *)runTheMatrix.py ${OVERRIDE_MATRIX_PARAMETERS} $JOB_REPORTS -s -j $(getconf _NPROCESSORS_ONLN) $MATRIX_EXTRAS 2>&1 | tee -a $WORKSPACE/matrixTests.log ;;
       esac

    fi
  popd
 
     
  if grep -i "ERROR executing" $WORKSPACE/matrixTests.log; then
    echo "Errors in the RelVals"

    echo 'MATRIX_TESTS;ERROR' >> $RESULTS_FILE
    echo 'COMPARISON;NOTRUN' >> $RESULTS_FILE

    ALL_OK=false
    RELVALS_OK=false
  else  
    echo "no errors in the RelVals!!"
    echo 'MATRIX_TESTS;OK' >> $RESULTS_FILE
    echo 'COMPARISON;QUEUED' >> $RESULTS_FILE

    TRIGGER_COMPARISON_FILE=$WORKSPACE/'comparison.properties'
    echo "Creating properties file $TRIGGER_COMPARISON_FILE"
    echo "RELEASE_FORMAT=$RELEASE_FORMAT" > $TRIGGER_COMPARISON_FILE
    echo "ARCHITECTURE=${ARCHITECTURE}" >> $TRIGGER_COMPARISON_FILE
    echo "PULL_REQUEST_NUMBER=$PULL_REQUEST_NUMBER" >> $TRIGGER_COMPARISON_FILE
    echo "PULL_REQUEST_JOB_ID=${BUILD_NUMBER}" >> $TRIGGER_COMPARISON_FILE
 
   #####################################################################
   #### Run igprof
   #####################################################################
   # for now this is only run for 25202
   
  
  if [ "X$RUN_IGPROF" = Xtrue ]; then
    echo 'IGPROF;QUEQUED' >> $RESULTS_FILE

    TRIGGER_IGPROF_FILE=$WORKSPACE/'igprof.properties'
    echo "Creating properties file $TRIGGER_IGPROF_FILE"   
    echo "RELEASE_FORMAT=$RELEASE_FORMAT" > $TRIGGER_IGPROF_FILE
    echo "ARCHITECTURE=${ARCHITECTURE}" >> $TRIGGER_IGPROF_FILE
    echo "PULL_REQUEST_NUMBER=$PULL_REQUEST_NUMBER" >> $TRIGGER_IGPROF_FILE
    echo "PULL_REQUEST_JOB_ID=${BUILD_NUMBER}" >> $TRIGGER_IGPROF_FILE
    echo "LAST_COMMIT=${LAST_COMMIT}" >> $TRIGGER_IGPROF_FILE
    echo "AUTO_POST_MESSAGE=${AUTO_POST_MESSAGE}" >> $TRIGGER_IGPROF_FILE

  else  
    echo 'IGPROF;NOTRUN' >> $RESULTS_FILE
  fi

  #####################################################################
  #### Run cfg-viewer
  #####################################################################

    if [ "X$RUN_CONFIG_VIEWER" = Xtrue ]; then

      mkdir -p "$WORKSPACE/cfg-viewerResults"
      pushd "$WORKSPACE/cfg-viewerResults"
      cfg-viewer.py -r -s "$WORKSPACE/runTheMatrix-results"
      popd
       sed -i "s/<!--CONFIG_FILES_BROWSER//g" $WORKSPACE/summary.html
       sed -i "s/CONFIG_FILES_BROWSER-->//g" $WORKSPACE/summary.html
       sed -i "s/PARAM_CONFIG_BROWSER/https:\/\/cmssdt.cern.ch\/SDT\/jenkins-artifacts\/pull-request-integration\/PR-${PULL_REQUEST}\/${BUILD_NUMBER}\/cfg-viewerResults\//g" $WORKSPACE/summary.html
    fi
  fi
  
else

  echo 'MATRIX_TESTS;NOTRUN' >> $RESULTS_FILE
  echo 'COMPARISON;NOTRUN' >> $RESULTS_FILE
  echo 'IGPROF;NOTRUN' >> $RESULTS_FILE

fi

#
# Duplicate checks
#
if [ "X$DO_DUPLICATE_CHECKS" = Xtrue -a "$ONLY_FIREWORKS" = false ]; then
  pushd $CMSSW_BASE/src
  eval `scram run -sh`
  echo '--------------------------------------'
  echo "check dup dicts"
  duplicateReflexLibrarySearch.py --dir ./ --dup 2>&1 | tee -a $WORKSPACE/duplicateChecks.log
  echo "check wrong dict locations"
  duplicateReflexLibrarySearch.py --dir ./ --lostDefs 2>&1 | tee -a $WORKSPACE/duplicateChecks.log
  echo "check dup plugins"
  duplicateReflexLibrarySearch.py   --edmPD 2>&1 | tee -a $WORKSPACE/duplicateChecks.log
  echo '--------------------------------------'
  popd
fi

#
# Valgrind tests
#
for WF in ${WORKFLOWS_FOR_VALGRIND_TEST//,/ }; do 
  if [ "X$AUTO_POST_MESSAGE" = Xtrue ]; then
    $WORKSPACE/report-pull-request-results TESTS_RUNNING --pr $PULL_REQUEST_NUMBER -c $LAST_COMMIT --pr-job-id $PULL_REQUEST_JOB_ID --add-message "Running Valgrind"
  fi  
  echo 'I will run valgrind for the following workflow'
  echo $WF; 
  mkdir -p "$WORKSPACE/valgrindResults-"$WF
  pushd "$WORKSPACE/valgrindResults-"$WF
  runTheMatrix.py --command '-n 10 --prefix "time valgrind --tool=memcheck --suppressions=$CMSSW_RELEASE_BASE/src/Utilities/ReleaseScripts/data/cms-valgrind-memcheck.supp --num-callers=20 --xml=yes --xml-file=valgrind.xml " ' -l $WF  
  popd
done
ls


#
# If auto post is selected...
#
if [ "X$AUTO_POST_MESSAGE" = Xtrue ]; then
  if $ALL_OK ; then
     echo $ALL_OK
     $WORKSPACE/report-pull-request-results TESTS_OK_PR --pr $PULL_REQUEST_NUMBER -c $LAST_COMMIT --pr-job-id $PULL_REQUEST_JOB_ID
  elif [ "X$BUILD_OK" = Xfalse ]; then
     echo $BUILD_OK
     $WORKSPACE/report-pull-request-results PARSE_BUILD_FAIL --pr $PULL_REQUEST_NUMBER -c $LAST_COMMIT --pr-job-id $PULL_REQUEST_JOB_ID --unit-tests-file $WORKSPACE/build.log
  elif [ "X$UNIT_TESTS_OK" = Xfalse ]; then
     echo $UNIT_TESTS_OK
     echo 'failure in unit tests'
     $WORKSPACE/report-pull-request-results PARSE_UNIT_TESTS_FAIL --pr $PULL_REQUEST_NUMBER -c $LAST_COMMIT --pr-job-id $PULL_REQUEST_JOB_ID --unit-tests-file $WORKSPACE/unitTests.log
  elif [ "X$RELVALS_OK" = Xfalse ]; then
     pushd $WORKSPACE/
     ./report-pull-request-results PARSE_MATRIX_FAIL --pr $PULL_REQUEST_NUMBER -c $LAST_COMMIT --pr-job-id $PULL_REQUEST_JOB_ID --unit-tests-file $WORKSPACE/matrixTests.log
     popd
  fi
fi
