#!/bin/sh -ex

# Parameters set by jenkins:
# ARCHITECTURE
# RELEASE_FORMAT
# WORKSPACE
voms-proxy-init
ls /cvmfs/cms-ib.cern.ch || true
SCRAM_ARCH=$ARCHITECTURE
scram p $RELEASE_FORMAT
cd $RELEASE_FORMAT/src
eval `scram run -sh`
git cms-addpkg HLTrigger/Configuration
scram build -j $(getconf _NPROCESSORS_ONLN)
cd HLTrigger/Configuration/test/
ls
./runAll.csh IB | tee -a $WORKSPACE/results/runIB.log
./examLogs.csh | tee -a $WORKSPACE/results/examLogs.out
ls
mkdir -p $WORKSPACE/results
cp *.log $WORKSPACE/results
cp *.out $WORKSPACE/results
