#!/bin/sh -ex

function Jenkins_GetCPU ()
{
  ACTUAL_CPU=$(getconf _NPROCESSORS_ONLN)
  case $NODE_NAME in
    lxplus* ) ACTUAL_CPU=$(echo $ACTUAL_CPU / 2 | bc) ;;
  esac
  if [ "X$1" != "X" ] ; then
    ACTUAL_CPU=$(echo "$ACTUAL_CPU*$1" | bc)
  fi
  echo $ACTUAL_CPU
}
ls /cvmfs/cms-ib.cern.ch || true
export SCRAM_ARCH=$ARCHITECTURE
scram project $RELEASE_FORMAT
cd $RELEASE_FORMAT
eval `scram run -sh`
mkdir -p "$WORKSPACE/matrix-results"
pushd "$WORKSPACE/matrix-results"

  case $RELEASE_FORMAT in 
    *THREADED*)
    echo "Threaded!"
    THREADED_PARAM='--command \"--customise FWCore/Concurrency/dropNonMTSafe.dropNonMTSafe\"'
    ;;
  esac

  runTheMatrix.py $THREADED_PARAM -s -j $(Jenkins_GetCPU) -l 1306.0,101.0,1003.0,50202.0,9.0,25202.0 2>&1 | tee -a $WORKSPACE/matrixTests.log

  MAPPING_FILE=wf_mapping.txt
  ROOT_FILES=`find . -name DQM*.root | sort`
  PKGTOOLS_PATH=$WORKSPACE/pkgtools
  for f in $ROOT_FILES
  do
    WF_PATH=`echo $f | sed 's/^\.\///'`
    WF_NUMBER=`echo $WF_PATH | sed 's/_.*$//'`
    echo $WF_PATH >> $MAPPING_FILE
  done

popd

ERRORS_FILE=$WORKSPACE/wf_errors.txt
touch $ERRORS_FILE

grep "ERROR executing.*" $WORKSPACE/matrixTests.log | while read line
do
  WF_STEP=`echo "$line" | sed 's/.* cd //g' | sed 's/_.*step/;/g' | sed 's/_.*$//g'`
  # don't add duplicate lines
  if ! grep $WF_STEP $ERRORS_FILE; then
    echo $WF_STEP >> $ERRORS_FILE
  fi
done

# Make it fail so it can be identified when there were errors
if grep -i -E "ERROR executing.*" $WORKSPACE/matrixTests.log; then
  echo "Errors in the RelVals"
  exit 1
fi
