#!/bin/bash -ex

eval `scram run -sh`
mkdir $LOCALRT/run
cd $LOCALRT/run
cmsRun $CMSSW_RELEASE_BASE/src/Validation/Geometry/python/single_neutrino_cfg.py >single_neutrino_cfg.log 2>&1
scram b disable-biglib
eval `scram run -sh`

#Workaround for patch release where scram is not dropping biglib path from base release
#following is done to avoid a bug in scram
export LD_LIBRARY_PATH=$(echo $LD_LIBRARY_PATH | tr ':' '\n' | grep -v /biglib/$SCRAM_ARCH | tr '\n' ':')

cmsRun $CMSSW_RELEASE_BASE/src/Validation/Geometry/test/runP_Tracker_cfg.py >runP_Tracker_cfg.log 2>&1
mkdir Images
cp $CMSSW_RELEASE_BASE/src/Validation/Geometry/test/MaterialBudget.C .
root -b -q 'MaterialBudget.C("Tracker")' || true

SSH_OPTS="-o IdentitiesOnly=yes -o PubkeyAuthentication=no -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ServerAliveInterval=60"
for i in 1 2 3 4 5 ;  do
  echo Trying to upload results $i
  ( ssh $SSH_OPTS cmsbuild@cmssdtprod.cern.ch mkdir -p /data/sdt/SDT/jenkins-artifacts/il-budget/$CMSSW_VERSION && \
    rsync -az -e "ssh $SSH_OPTS" $LOCALRT/run/ cmsbuild@cmssdtprod.cern.ch:/data/sdt/SDT/jenkins-artifacts/il-budget/$CMSSW_VERSION/ ) && break
  sleep 120
done
