#!/bin/bash
echo "#!/bin/bash -ex"
echo "set +x"
echo "ls /cvmfs/cms-ib.cern.ch >/dev/null 2>&1 || true"
echo "ls /cvmfs/cms.cern.ch >/dev/null 2>&1 || true"
echo "export ARCHITECTURE=${ARCHITECTURE}"
echo "export RELEASE_FORMAT=${RELEASE_FORMAT}"
echo "source $CMS_PATH/cmsset_default.sh  || true"
echo "scram -a $ARCHITECTURE project $RELEASE_FORMAT"
echo "cp $WORKSPACE/cms-bot/das-utils/das_client $WORKSPACE/cms-bot/das-utils/das_client.py"
echo "cd $RELEASE_FORMAT"
echo 'eval `scram runtime -sh`'
echo "$WORKSPACE/cms-bot/das-utils/use-ibeos-sort"
echo "export CMS_PATH=/cvmfs/cms-ib.cern.ch/week0"
echo "export PATH=$WORKSPACE/cms-bot/das-utils:\$PATH"
echo "export FRONTIER_LOG_LEVEL=warning"
echo "set -x"
