#!/bin/bash -ex
PULL_REQUEST=$1
NUM_PROC=$(getconf _NPROCESSORS_ONLN)
case $(hostname) in lxplus* ) let NUM_PROC=$NUM_PROC/2 ;; esac
if [ $NUM_PROC = "0" ] ; then NUM_PROC=1; fi
cd $CMSSW_BASE
git cms-merge-topic -u ${PULL_REQUEST} 2>&1 | tee cms-merge-topic.log
scram build -j $NUM_PROC code-checks   2>&1 | tee code-checks.log
rm -rf run-pr-format
mv ${CMSSW_BASE}/tmp/${SCRAM_ARCH}/code-checks-logs run-pr-format
mv cms-merge-topic.log run-pr-format/
mv code-checks.log run-pr-format/
cd $CMSSW_BASE/src
git diff > ${CMSSW_BASE}/run-pr-format/git.diff

