#!/bin/sh -ex
BASE_URL=$ARTIFACTS_MACHINE:/data/sdt/SDT/jenkins-artifacts/ib-baseline-tests/$RELEASE_FORMAT/$ARCHITECTURE/$REAL_ARCH/matrix-results/
PULL_REQUEST_BASE_URL=$ARTIFACTS_MACHINE:/data/sdt/SDT/jenkins-artifacts/pull-request-integration/PR-$PULL_REQUEST_NUMBER/$PULL_REQUEST_JOB_ID/runTheMatrix-results/

MAPPING_FILE=wf_mapping.txt
rsync $BASE_URL$MAPPING_FILE $WORKSPACE

for wf in ${WORKFLOWS_LIST//,/ }
do
  WF_PATH=`grep $wf $WORKSPACE/$MAPPING_FILE`
  WORKFLOWS_TO_COMPARE=$WORKFLOWS_TO_COMPARE,$WF_PATH
done

#remove first ,
WORKFLOWS_TO_COMPARE=`echo $WORKFLOWS_TO_COMPARE | sed 's/^.//'`

DETAILS_FILE=$WORKSPACE/'comparisonDetails.txt'
echo 'BASE_IB;'$RELEASE_FORMAT >> $DETAILS_FILE
echo 'PR_NUMBER;'$PULL_REQUEST_NUMBER >> $DETAILS_FILE
echo 'ADDITIONAL_PRS;'$ADDITIONAL_PULL_REQUESTS >> $DETAILS_FILE
echo 'ARCHITECTURE;'$ARCHITECTURE >> $DETAILS_FILE
echo 'REAL_ARCH;'$REAL_ARCH >> $DETAILS_FILE
echo 'MACHINE ARCHITECTURE:' >> $DETAILS_FILE
cat /proc/cpuinfo |  grep "model name" >> $DETAILS_FILE

export SCRAM_ARCH=$ARCHITECTURE
scram project $RELEASE_FORMAT
cd $RELEASE_FORMAT
eval `scram run -sh`
git cms-addpkg Utilities/RelMon
cd ..

mkdir $WORKSPACE/results
cd $WORKSPACE/results

# --------------------------------------------------------------------------
# Download the Files
# --------------------------------------------------------------------------
mkdir $WORKSPACE/results/files
cd $WORKSPACE/results/files

for WF in ${WORKFLOWS_TO_COMPARE//,/ }; do
  
  echo '#######################################'
  echo 'downloading:'
  echo $WF

  WF_BASE_URL=$BASE_URL$WF
  WF_PR_URL=$PULL_REQUEST_BASE_URL$WF
  WF_FILE=$(basename $WF)

  WF_DIR=`echo $WF | cut -d "/" -f1`

  mkdir $WORKSPACE/results/files/$WF_DIR
  cd $WORKSPACE/results/files/$WF_DIR

    rsync $WF_BASE_URL $WORKSPACE/results/files/$WF_DIR/$RELEASE_FORMAT-$WF_FILE
    rsync $WF_PR_URL $WORKSPACE/results/files/$WF_DIR/$PULL_REQUEST_NUMBER-$WF_FILE

  cd ..

done

cd ..

echo 'Finished downloading files:'

rsync $ARTIFACTS_MACHINE:/data/sdt/SDT/jenkins-artifacts/pull-request-integration/PR-$PULL_REQUEST_NUMBER/$PULL_REQUEST_JOB_ID/testsResults.txt $WORKSPACE/results/testsResults.txt
sed -i "s/COMPARISON;QUEUED/COMPARISON;RUNNING/g" $WORKSPACE/results/testsResults.txt
rsync $WORKSPACE/results/testsResults.txt $ARTIFACTS_MACHINE:/data/sdt/SDT/jenkins-artifacts/pull-request-integration/PR-$PULL_REQUEST_NUMBER/$PULL_REQUEST_JOB_ID/testsResults.txt


pwd
ls -R

# --------------------------------------------------------------------------
# Default Comparison
# --------------------------------------------------------------------------

if [ "X$RUN_DEFAULT_COMP" = Xtrue ]; then

  mkdir $WORKSPACE/results/default-comparison

  for WF in ${WORKFLOWS_TO_COMPARE//,/ }; do 

    WF_BASE_URL=$BASE_URL$WF
    WF_PR_URL=$PULL_REQUEST_BASE_URL$WF
    WF_FILE=$(basename $WF)
    WF_DIR=`echo $WF | cut -d "/" -f1`

    WF_NUMBER=`echo $WF | cut -d'_' -f1`

    #create the output dir
    OUTPUT_DIR=$WORKSPACE/results/default-comparison/$WF_DIR
    mkdir -p $OUTPUT_DIR

    #requires checking out Utilities/RelMon from the release.

    # create a mini script for running this comparisons in parallel
    echo '#!/bin/sh -ex' >> $WORKSPACE/results/default-comparison/command-$WF_NUMBER
    echo 'compare_using_files.py '$WORKSPACE'/results/files/'$WF_DIR'/'$RELEASE_FORMAT'-'$WF_FILE' '$WORKSPACE'/results/files/'$WF_DIR'/'$PULL_REQUEST_NUMBER'-'$WF_FILE' -o '$OUTPUT_DIR' --metas " '$RELEASE_FORMAT' @@@ '$RELEASE_FORMAT' + '$PULL_REQUEST_NUMBER' " --use_black_file -C -R -p --no_successes -s b2b --standalone 2>&1 | tee -a '$OUTPUT_DIR'RelMonComp-'$WF_NUMBER'.log' >> $WORKSPACE/results/default-comparison/command-$WF_NUMBER

    echo "pushd $OUTPUT_DIR" >> $WORKSPACE/results/default-comparison/command-$WF_NUMBER
    echo "cp RelMonSummary.html index.html" >> $WORKSPACE/results/default-comparison/command-$WF_NUMBER
    echo 'find . -name "*" | xargs sh -c "sed -i -s 's/..\/RelMonSummary.html/RelMonSummary.html/g' || true"' >> $WORKSPACE/results/default-comparison/command-$WF_NUMBER
    echo "popd" >> $WORKSPACE/results/default-comparison/command-$WF_NUMBER

    chmod 755 $WORKSPACE/results/default-comparison/command-$WF_NUMBER

    # execute the script
    $WORKSPACE/results/default-comparison/command-$WF_NUMBER &

  done

  jobs
  wait

  echo 'Finished with default comparison'

fi

# --------------------------------------------------------------------------
# JR-Comparison
# --------------------------------------------------------------------------

if [ "X$RUN_JR_COMP" = Xtrue ]; then

  JR_COMP_DIR=$WORKSPACE/results/JR-comparison

  mkdir -p $JR_COMP_DIR

  cp $WORKSPACE/cms-bot/comparisons/validateJR.sh $JR_COMP_DIR
  cp $WORKSPACE/cms-bot/comparisons/validate.C $JR_COMP_DIR
  cp $WORKSPACE/cms-bot/comparisons/matrix_70X.txt $JR_COMP_DIR

  mkdir -p $HOME/tools
  cp $WORKSPACE/cms-bot/comparisons/validate.C $HOME/tools

  #Download the baseline files
  rsync -r $ARTIFACTS_MACHINE:/data/sdt/SDT/jenkins-artifacts/ib-baseline-tests/$RELEASE_FORMAT/$ARCHITECTURE/$REAL_ARCH/matrix-results/ $JR_COMP_DIR/$RELEASE_FORMAT

  #Download the files for the pr
  rsync -r $ARTIFACTS_MACHINE:/data/sdt/SDT/jenkins-artifacts/pull-request-integration/PR-$PULL_REQUEST_NUMBER/$PULL_REQUEST_JOB_ID/runTheMatrix-results/ $JR_COMP_DIR/PR-$PULL_REQUEST_NUMBER

  cd $JR_COMP_DIR
    source $JR_COMP_DIR/validateJR.sh $JR_COMP_DIR/PR-$PULL_REQUEST_NUMBER $JR_COMP_DIR/$RELEASE_FORMAT OldVSNew matrix_70X.txt 2>&1 | tee -a $JR_COMP_DIR/validateJR.log
  cd ..

  echo  'source '$JR_COMP_DIR'/validateJR.sh '$JR_COMP_DIR'/PR-'$PULL_REQUEST_NUMBER' '$JR_COMP_DIR'/'$RELEASE_FORMAT' OldVSNew matrix_70X.txt 2>&1 | tee -a '$JR_COMP_DIR'/validateJR.log' > $JR_COMP_DIR/command

  echo 'Finished with JR comparison:'

fi

# ----------------------------------------------------------------------------
# Alternative Comparison
# ----------------------------------------------------------------------------

if [ "X$RUN_ALT_COMP" = Xtrue ]; then

  ALT_COMP_DIR=$WORKSPACE/results/alternative-comparison
  mkdir -p $ALT_COMP_DIR
  DQM_COMP_PARAMS_FILE=$ALT_COMP_DIR/comparisonParams.txt

  $WORKSPACE/cms-bot/comparisons/analyzeFWComparison.py $JR_COMP_DIR $DQM_COMP_PARAMS_FILE 2>&1 | tee -a $ALT_COMP_DIR/assignedParameters.log

  for WF in ${WORKFLOWS_TO_COMPARE//,/ }; do 

    WF_BASE_URL=$BASE_URL$WF
    WF_PR_URL=$PULL_REQUEST_BASE_URL$WF
    WF_FILE=$(basename $WF)
    WF_DIR=`echo $WF | cut -d "/" -f1`

    WF_NUMBER=`echo $WF | cut -d'_' -f1`

    BASE_FILE=$WORKSPACE/results/files/$WF_DIR/$RELEASE_FORMAT-$WF_FILE
    COMP_FILE=$WORKSPACE/results/files/$WF_DIR/$PULL_REQUEST_NUMBER-$WF_FILE
  
    mkdir -p $ALT_COMP_DIR/$WF_NUMBER

    cp $WORKSPACE/cms-bot/comparisons/compareValHists.C $ALT_COMP_DIR/$WF_NUMBER
    cp $WORKSPACE/cms-bot/comparisons/makeDiff.sh $ALT_COMP_DIR/$WF_NUMBER

    eval $( cat $DQM_COMP_PARAMS_FILE | grep "FOR_WF=$WF_NUMBER;" )

    echo $MOD

    # create a mini script for running this comparisons in parallel
    echo '#!/bin/sh -ex' >> $ALT_COMP_DIR/command-$WF_NUMBER
    echo "pushd $ALT_COMP_DIR/$WF_NUMBER" >> $ALT_COMP_DIR/command-$WF_NUMBER
    echo "source $ALT_COMP_DIR/$WF_NUMBER/makeDiff.sh $BASE_FILE $COMP_FILE $WF_NUMBER-result.ps 0 $MOD 2>&1 | tee -a $ALT_COMP_DIR/runDQMComp-$WF_NUMBER.log" >> $ALT_COMP_DIR/command-$WF_NUMBER
    echo "mv diff.ps $ALT_COMP_DIR/$WF_NUMBER-result.ps || true" >> $ALT_COMP_DIR/command-$WF_NUMBER
    echo "mv diff.pdf $ALT_COMP_DIR/$WF_NUMBER-result.pdf || true" >> $ALT_COMP_DIR/command-$WF_NUMBER
    echo "gzip -f $ALT_COMP_DIR/$WF_NUMBER-result.ps || true" >> $ALT_COMP_DIR/command-$WF_NUMBER
    echo "gzip -f $ALT_COMP_DIR/$WF_NUMBER-result.pdf || true" >> $ALT_COMP_DIR/command-$WF_NUMBER
    echo "popd" >> $ALT_COMP_DIR/command-$WF_NUMBER

    chmod 755 $ALT_COMP_DIR/command-$WF_NUMBER
    $ALT_COMP_DIR/command-$WF_NUMBER &

  done

  jobs
  wait

  echo 'Finished with alternative comparison:'

fi

sed -i "s/COMPARISON;RUNNING/COMPARISON;$BUILD_NUMBER/g" $WORKSPACE/results/testsResults.txt
rsync $WORKSPACE/results/testsResults.txt $ARTIFACTS_MACHINE:/data/sdt/SDT/jenkins-artifacts/pull-request-integration/PR-$PULL_REQUEST_NUMBER/$PULL_REQUEST_JOB_ID/testsResults.txt




