#!/bin/bash -ex
PULL_REQUEST=$1
CMS_BOT_DIR=$(dirname $0)
case $CMS_BOT_DIR in /*) ;; *) CMS_BOT_DIR=$(pwd)/${CMS_BOT_DIR} ;; esac
if [ "X${WORKSPACE}" = "X" ] ; then WORKSPACE=$(pwd) ; fi
rm -rf ${WORKSPACE}/upload && mkdir ${WORKSPACE}/upload

NUM_PROC=$(getconf _NPROCESSORS_ONLN)
case $(hostname) in lxplus* ) let NUM_PROC=$NUM_PROC/2 ;; esac
if [ $NUM_PROC = "0" ] ; then NUM_PROC=1; fi

cd $CMSSW_BASE/src
git cms-merge-topic -u ${PULL_REQUEST}
scram build -j ${NUM_PROC} llvm-ccdb > ${WORKSPACE}/upload/llvm-ccdb.log 2>&1
${CMS_BOT_DIR}/get-pr-changed-files cmssw ${PULL_REQUEST} > ${WORKSPACE}/upload/pr-changed-files-all.log
touch ${WORKSPACE}/upload/pr-changed-files-selected.log
for f in $(cat ${WORKSPACE}/upload/pr-changed-files-all.log | grep -v '/test/') ; do
  if [ $(grep "/src/$f\"" $CMSSW_BASE/compile_commands.json | wc -l) -gt 0 ] ; then 
    echo $f >> ${WORKSPACE}/upload/pr-changed-files-selected.log
  fi
done
USER_CODE_CHECK_FILES=$(cat ${WORKSPACE}/upload/pr-changed-files-selected.log | tr '\n' ' ')
if [ "${USER_CODE_CHECK_FILES}" != "" ] ; then 
  export USER_STYLE_CHECKS='boost-use-to-string,misc-string-compare,misc-uniqueptr-reset-release,modernize-deprecated-headers,modernize-make-shared,modernize-use-bool-literals,modernize-use-equals-delete,modernize-use-nullptr,modernize-use-override,performance-unnecessary-copy-initialization,readability-container-size-empty,readability-redundant-string-cstr,readability-static-definition-in-anonymous-namespace,readability-uniqueptr-delete-release'
  export USER_CODE_CHECK_FILES
  scram build -j ${NUM_PROC} style > ${WORKSPACE}/upload/clang-tidy.log 2>&1
  git diff > ${WORKSPACE}/upload/git-diff.patch
else
  touch ${WORKSPACE}/upload/git-diff.patch
fi
