#!/bin/bash -x
ARCHITECTURE=$1
RELEASE_FORMAT=$2
WORKSPACE="${WORKSPACE-$PWD}"
ls /cvmfs/cms-ib.cern.ch || true
cd $WORKSPACE
rm -rf llvm-analysis reports

export LC_ALL=C
export SCRAM_ARCH=$ARCHITECTURE
export J=$(getconf _NPROCESSORS_ONLN)
scram -a $SCRAM_ARCH project $RELEASE_FORMAT
cd $RELEASE_FORMAT
eval `scram run -sh`
git cms-addpkg "*"

cp -pv src/Utilities/StaticAnalyzers/scripts/*  $LOCALRT/tmp
cd $LOCALRT/tmp
chmod +x *.py *.sh
./run_class_dumper.sh $J
cp -pv $LOCALRT/tmp/bloom.bin $LOCALRT/src/Utilities/StaticAnalyzers/scripts/bloom.bin
./run_class_checker.sh $J

mv $LOCALRT/llvm-analysis/* $WORKSPACE/llvm-analysis
chmod -R a+r $WORKSPACE/llvm-analysis

./create_statics_esd_reports.sh
ls -ltrh
tar cvfz dumper-checker.tgz *.txt*
egrep '::(stream|global)::[^ ]+::(produce|analyze|filter)\(\)' modules2statics.txt | egrep -v 'edm::RootInputFileSequence::initTheFile\(\)' | egrep -v 'PrintGeomInfoAction::update\(\)'  > modules2statics-filter1.txt
mkdir $WORKSPACE/reports
for f in dumper-checker.tgz esd2tlf.txt tlf2esd.txt statics2modules.txt modules2statics.txt override-flagged-classes.txt getparam-dumper.txt modules2statics-filter1.txt ; do
  [ -f $f ] && cp $f $WORKSPACE/reports/$f
done


