#!/bin/bash -x
WORKSPACE="${WORKSPACE-$PWD}"
export J=$(nproc)
export LC_ALL=C
cd $CMSSW_BASE
rm -rf src
git clone --reference /cvmfs/cms-ib.cern.ch/git/cms-sw/cmssw.git  --depth 1 git@github.com:cms-sw/cmssw src
cd src
git checkout $CMSSW_VERSION
rm -rf .git

cp -pv Utilities/StaticAnalyzers/scripts/*  $LOCALRT/tmp
cd $LOCALRT/tmp
chmod +x *.py *.sh
./run_class_dumper.sh $J
cp -pv $LOCALRT/tmp/bloom.bin $LOCALRT/src/Utilities/StaticAnalyzers/scripts/bloom.bin
./run_class_checker.sh $J

mv $LOCALRT/llvm-analysis/* $WORKSPACE/llvm-analysis
chmod -R a+r $WORKSPACE/llvm-analysis
#if postprocess-scan-build.py exists then run it
if [ -e ./postprocess-scan-build.py ] ; then
  ./postprocess-scan-build.py $WORKSPACE/llvm-analysis/index.html > $WORKSPACE/llvm-analysis/index-bs.html 2>&1
  mv $WORKSPACE/llvm-analysis/index-bs.html $WORKSPACE/llvm-analysis/index.html
fi

./create_statics_esd_reports.sh
ls -ltrh
tar cvfz dumper-checker.tgz *.txt*
egrep '::(stream|global)::[^ ]+::(produce|analyze|filter)\(\)' modules2statics.txt | egrep -v 'edm::RootInputFileSequence::initTheFile\(\)' | egrep -v 'PrintGeomInfoAction::update\(\)'  > modules2statics-filter1.txt
mkdir $WORKSPACE/reports
for f in dumper-checker.tgz esd2tlf.txt tlf2esd.txt statics2modules.txt modules2statics.txt override-flagged-classes.txt getparam-dumper.txt modules2statics-filter1.txt ; do
  [ -f $f ] && cp $f $WORKSPACE/reports/$f
done


