#!/usr/bin/env python
from _py2with3compatibility import urlopen
from json import loads
from os import system
from sys import exit
ip_file="/data/sdt/github-hook-meta.txt"
ip_net =loads(urlopen("https://api.github.com/meta").readlines()[0])['hooks'][0].encode()
if ip_net:
  system("echo " + ip_net + ">" + ip_file + ".tmp ; mv "+ip_file + ".tmp "+ip_file);
else:
  exit(1)
