#!/bin/sh -ex

# This script assumes that the release is built without errors in the directory 
# /build/cmsbuild/auto-builds/$CMSSW_X_Y_Z-$ARCHITECTURE/build
# CMSSW_X_Y_Z: the release to upload
# ARCHITECTURE: architecture for the upload
# ISSUE_NUMBER: the number of the issue that triggered the upload
# DRY_RUN_PARAM: parameter that to use dry-run

CMSSW_X_Y_Z=not-assigned
ARCHITECTURE=not-assigned
ISSUE_NUMBER=not-assigned
DRY_RUN_PARAM=not-assigned
BUILD_NUMBER=not-assigned
WORKSPACE=${WORKSPACE-"/build/cmsbuild/auto-builds/$CMSSW_X_Y_Z-$ARCHITECTURE/"}

HERE=$WORKSPACE/build
BUILD_DIR=$HERE/$CMSSW_X_Y_Z-build
case $CMSSW_X_Y_Z in
    *patch*) 
      PATCH='-patch';;
    *) 
     /afs/cern.ch/cms/sdt/internal/scripts/requestNewAfsSpace.py --platform $ARCHITECTURE --version $CMSSW_X_Y_Z; 
    ;; 
esac

WORKER=`hostname -s`

# the jenkins build number is the one of the job in jenkins doing the upload
$WORKSPACE/report-build-release-status $BUILD_NUMBER $WORKER $ISSUE_NUMBER $ARCHITECTURE $CMSSW_X_Y_Z UPLOADING $DRY_RUN_PARAM
pushd $BUILD_DIR
  PKGTOOLS/cmsBuild --architecture=$ARCHITECTURE --sync-back upload cmssw$PATCH
popd

echo 'ALL_OK'
