WATCHERS = {
  "alja": ["Fireworks"],
  "ghellwig": ["Alignment", "CalibTracker/Configuration", "CondCore", "Configuration", "Geometry", "RecoTracker"],
  "wmtan": [
    "DataFormats/Common", "DataFormats/FWLite", "DataFormats/FEDRawData",
    "DataFormats/Provenance", "DataFormats/StdDictionaries",
    "DataFormats/Streamer", "DataFormats/TestObjects",
    "DataFormats/WrappedStdDictionaries", "FWCore", "IOMC/RandomEngine", "IOPool",
    "IORawData/DaqSource", "Mixing", "SimDataFormats/RandomEngine",
    "SimGeneral/DataMixingModule", "SimGeneral/MixingModule"],
  "TaiSakuma": [
    "CondFormats/JetMETObjects",
    "DQMOffline/JetMET",
    "DataFormats/JetReco",
    "DataFormats/METReco",
    "JetMETCorrections",
    "PhysicsTools/PatAlgos",
    "PhysicsTools/PatUtils",
    "PhysicsTools/RecoAlgos",
    "RecoJets",
    "RecoMET",
    "Validation/RecoJets",
    "Validation/RecoMET"],
  "cerati" : [
    "RecoTracker",
    "RecoLocalTracker",
    "TrackingTools",
    "SimTracker",
    "SimGeneral/TrackingAnalysis",
    "RecoVertex",
    "RecoPixelVertexing",
    "Configuration/StandardSequences",
    "Validation/RecoTrack",
    "Validation/RecoVertex",
  ],
  "GiacomoSguazzoni" : [
    "RecoTracker",
    "RecoLocalTracker",
    "TrackingTools",
    "SimTracker",
    "SimGeneral/TrackingAnalysis",
    "RecoVertex",
    "RecoPixelVertexing",
    "Configuration/StandardSequences",
    "Validation/RecoTrack",
    "Validation/RecoVertex",
  ],
  "rovere" : [
    "RecoTracker",
    "RecoLocalTracker",
    "TrackingTools",
    "SimTracker",
    "SimGeneral/TrackingAnalysis",
    "RecoVertex",
    "RecoPixelVertexing",
    "Configuration/StandardSequences",
    "Validation/RecoTrack",
    "Validation/RecoVertex",
  ],
  "valuev": [
    "L1Trigger/CSCTriggerPrimitives",
  ],
  "ferencek": [
    "DataFormats/BTauReco",
    "DQMOffline/RecoB",
    "SimDataFormats/JetMatching",
    "HLTriggerOffline/Btag",
    "HLTrigger/btau",
    "PhysicsTools/JetExamples",
    "PhysicsTools/JetMCAlgos",
    "PhysicsTools/JetMCUtils",
    "RecoJets/JetAssociationAlgorithms",
    "RecoJets/JetAssociationProducers",
    "RecoVertex/AdaptiveVertexFinder",
    "RecoVertex/AdaptiveVertexFit",
    "Validation/RecoB",
  ],
  "jpavel": [
    "RecoTautag",
    "DataFormats/TauReco",
  ],
  "gpetruc": [
     "DataFormats/Track"
     "DataFormats/Trajectory",
     "RecoLocalTracker",
     "RecoTracker",
     "TrackingTools",
  ],
  "pakhotin": [
      "Alignment/MuonAlignment",
      "Alignment/MuonAlignmentAlgorithms",
      "Alignment/CommonAlignment",
      "Alignment/CommonAlignmentAlgorithm",
      "Alignment/CommonAlignmentMonitor",
      "Alignment/CommonAlignmentProducer",
      "Alignment/CommonAlignmentParametrization"
  ]
}
