WATCHERS = {
  "alja": ["Fireworks"],
  "acaudron": ["DQMOffline/RecoB", "Validation/RecoB"],
  "argiro": [".*[Ee][Cc][Aa][Ll].*"],
  "bachtis": ["DataFormats/ParticleFlowReco", "DataFormats/ParticleFlowCandidate", "RecoParticleFlow"],
  "ghellwig": ["Alignment", "CalibTracker/Configuration", "CondCore", "Configuration", "Geometry", "RecoTracker"],
  "wmtan": [
    "DataFormats/Common", "DataFormats/FWLite", "DataFormats/FEDRawData",
    "DataFormats/Provenance", "DataFormats/StdDictionaries",
    "DataFormats/Streamer", "DataFormats/TestObjects",
    "DataFormats/WrappedStdDictionaries", "FWCore", "IOMC/RandomEngine", "IOPool",
    "IORawData/DaqSource", "Mixing", "SimDataFormats/RandomEngine",
    "SimGeneral/DataMixingModule", "SimGeneral/MixingModule"],
  "TaiSakuma": [
    "CondFormats/JetMETObjects",
    "DQMOffline/JetMET",
    "DataFormats/JetReco",
    "DataFormats/METReco",
    "JetMETCorrections",
    "PhysicsTools/PatAlgos",
    "PhysicsTools/PatUtils",
    "PhysicsTools/RecoAlgos",
    "RecoJets",
    "RecoMET",
    "Validation/RecoJets",
    "Validation/RecoMET"],
  "nhanvtran": [
    "CondFormats/JetMETObjects",
    "DQMOffline/JetMET",
    "DataFormats/JetReco",
    "DataFormats/METReco",
    "JetMETCorrections",
    "PhysicsTools/PatAlgos",
    "PhysicsTools/PatUtils",
    "PhysicsTools/RecoAlgos",
    "RecoJets",
    "RecoMET",
    "Validation/RecoJets",
    "Validation/RecoMET"],
  "cerati" : [
    "RecoTracker",
    "RecoLocalTracker",
    "TrackingTools",
    "SimTracker",
    "SimGeneral/TrackingAnalysis",
    "RecoVertex",
    "RecoPixelVertexing",
    "Configuration/StandardSequences",
    "Validation/RecoTrack",
    "Validation/RecoVertex",
  ],
  "GiacomoSguazzoni" : [
    "RecoTracker",
    "RecoLocalTracker",
    "TrackingTools",
    "SimTracker",
    "SimGeneral/TrackingAnalysis",
    "RecoVertex",
    "RecoPixelVertexing",
    "Configuration/StandardSequences",
    "Validation/RecoTrack",
    "Validation/RecoVertex",
  ],
  "rovere" : [
    "RecoTracker",
    "RecoLocalTracker",
    "TrackingTools",
    "SimTracker",
    "SimGeneral/TrackingAnalysis",
    "RecoVertex",
    "RecoPixelVertexing",
    "Configuration/StandardSequences",
    "Validation/RecoTrack",
    "Validation/RecoVertex",
  ],
  "valuev": [
    "L1Trigger/CSCTriggerPrimitives",
  ],
  "ferencek": [
    "CondFormats/BTauObjects",
    "DataFormats/BTauReco",
    "DQMOffline/RecoB",
    "SimDataFormats/JetMatching",
    "HLTriggerOffline/Btag",
    "HLTrigger/btau",
    "PhysicsTools/JetExamples",
    "PhysicsTools/JetMCAlgos",
    "PhysicsTools/JetMCUtils",
    "RecoBTag",
    "RecoBTau",
    "RecoJets/JetAssociationAlgorithms",
    "RecoJets/JetAssociationProducers",
    "RecoVertex/AdaptiveVertexFinder",
    "RecoVertex/AdaptiveVertexFit",
    "Validation/RecoB",
  ],
  "pvmulder": [
    "CondFormats/BTauObjects",
    "DataFormats/BTauReco",
    "DQMOffline/RecoB",
    "SimDataFormats/JetMatching",
    "HLTriggerOffline/Btag",
    "HLTrigger/btau",
    "PhysicsTools/JetExamples",
    "PhysicsTools/JetMCAlgos",
    "PhysicsTools/JetMCUtils",
    "RecoBTag",
    "RecoBTau",
    "RecoJets/JetAssociationAlgorithms",
    "RecoJets/JetAssociationProducers",
    "RecoVertex/AdaptiveVertexFinder",
    "RecoVertex/AdaptiveVertexFit",
    "Validation/RecoB",
  ],
  "jpavel": [
    "RecoTauTag",
    "DataFormats/TauReco",
  ],
  "gpetruc": [
     "DataFormats/Track"
     "DataFormats/Trajectory",
     "RecoLocalTracker",
     "RecoTracker",
     "TrackingTools",
  ],
  "pakhotin": [
      "Alignment/MuonAlignment",
      "Alignment/MuonAlignmentAlgorithms",
      "Alignment/CommonAlignment",
      "Alignment/CommonAlignmentAlgorithm",
      "Alignment/CommonAlignmentMonitor",
      "Alignment/CommonAlignmentProducer",
      "Alignment/CommonAlignmentParametrization"
  ],
  "frmeier": [
      "Alignment/CommonAlignment",
      "Alignment/CommonAlignmentAlgorithm",
      "Alignment/CommonAlignmentParametrization",
      "Alignment/CommonAlignmentProducer",
      "Alignment/MillePedeAlignmentAlgorithm",
      "Alignment/OfflineValidation",
      "Alignment/ReferenceTrajectories",
      "Alignment/SurveyAnalysis",
      "Alignment/TrackerAlignment",
      "Alignment/TwoBodyDecay",
      "MuonAnalysis/MomentumScaleCalibration",
  ],
  "mmusich": [
      "Alignment/CommonAlignment",
      "Alignment/CommonAlignmentAlgorithm",
      "Alignment/CommonAlignmentParametrization",
      "Alignment/CommonAlignmentProducer",
      "Alignment/MillePedeAlignmentAlgorithm",
      "Alignment/OfflineValidation",
      "Alignment/ReferenceTrajectories",
      "Alignment/SurveyAnalysis",
      "Alignment/TrackerAlignment",
      "Alignment/TwoBodyDecay",
      "MuonAnalysis/MomentumScaleCalibration",
  ],
  "inugent": [
    "GeneratorInterface/ExternalDecays",
    "Validation/EventGenerator"
  ],
  "mandrenguyen": ["RecoHI", "HeavyIonsAnalysis", "DataFormats/HeavyIonEvent"],
  "yetkinyilmaz": ["RecoHI", "HeavyIonsAnalysis", "DataFormats/HeavyIonEvent"],
  "richard-cms": ["RecoHI", "Validation/RecoHI", "Validation/RecoEgamma"],
  "kkrajczar": ["Validation/RecoHI"],
  "rylanC24": ["Validation/RecoHI"],
  "yenjie": ["RecoHI"],
  "yslai": ["RecoHI/HiJetAlgos", "RecoJets/JetProducers", "DataFormats/HeavyIonEvent"],
  "cbaus": [
      "GeneratorInterface/ReggeGribovPartonMCInterface",
      "GeneratorInterface/HiGenCommon", 
      "GeneratorInterface/HydjetInterface", 
      "GeneratorInterface/PyquenInterface"
  ],
  "kurtejung": ["RecoHI"],
  "jazzitup": ["RecoHI"],
  "azsigmon": ["RecoHI"],
  "bachtis": ["RecoMuon", "DataFormats/MuonReco"],
  "venturia": ["DPGAnalysis/SiStripTools", 
               "Validation/RecoVertex",
               "DQM/SiStripMonitorSummary", 
               "DQM/SiStripMonitorClient", 
               "CommonTools/TrackerMap"],
  "azsigmon": ["RecoHI/HiCentralityAlgos", "DataFormats/HeavyIonEvent"],
  "miheejo": ["RecoHI/HiMuonAlgos", "RecoHI/Configuration"],
}
