WATCHERS = {
  "alja": ["Fireworks"],
  "ghellwig": ["Alignment", "CalibTracker/Configuration", "CondCore", "Configuration", "Geometry", "RecoTracker"],
  "wmtan": [
    "DataFormats/Common", "DataFormats/FWLite", "DataFormats/FEDRawData",
    "DataFormats/Provenance", "DataFormats/StdDictionaries",
    "DataFormats/Streamer", "DataFormats/TestObjects",
    "DataFormats/WrappedStdDictionaries", "FWCore", "IOMC/RandomEngine", "IOPool",
    "IORawData/DaqSource", "Mixing", "SimDataFormats/RandomEngine",
    "SimGeneral/DataMixingModule", "SimGeneral/MixingModule"],
  "TaiSakuma": [
    "CondFormats/JetMETObjects",
    "DQMOffline/JetMET",
    "DataFormats/JetReco",
    "DataFormats/METReco",
    "JetMETCorrections",
    "PhysicsTools/PatAlgos",
    "PhysicsTools/PatUtils",
    "PhysicsTools/RecoAlgos",
    "RecoJets",
    "RecoMET",
    "Validation/RecoJets",
    "Validation/RecoMET"],
  "cerati" : [
    "RecoTracker",
    "RecoLocalTracker",
    "TrackingTools",
    "SimTracker",
    "SimGeneral/TrackingAnalysis",
    "RecoVertex",
    "RecoPixelVertexing",
    "Configuration/StandardSequences",
    "Validation/RecoTrack",
    "Validation/RecoVertex",
  ],
  "GiacomoSguazzoni" : [
    "RecoTracker",
    "RecoLocalTracker",
    "TrackingTools",
    "SimTracker",
    "SimGeneral/TrackingAnalysis",
    "RecoVertex",
    "RecoPixelVertexing",
    "Configuration/StandardSequences",
    "Validation/RecoTrack",
    "Validation/RecoVertex",
  ],
  "rovere" : [
    "RecoTracker",
    "RecoLocalTracker",
    "TrackingTools",
    "SimTracker",
    "SimGeneral/TrackingAnalysis",
    "RecoVertex",
    "RecoPixelVertexing",
    "Configuration/StandardSequences",
    "Validation/RecoTrack",
    "Validation/RecoVertex",
  ],
  "valuev": [
    "L1Trigger/CSCTriggerPrimitives",
  ],
  "ferencek": [
    "RecoJets",
    "RecoBTag",
    "RecoBTau",
  ],
  "jpavel": [
    "RecoTautag",
    "DataFormats/TauReco",
  ],
  "gpetruc": [
     "DataFormats/Track"
     "DataFormats/Trajectory",
     "RecoLocalTracker",
     "RecoTracker",
     "TrackingTools",
  ]
}
