#!/bin/sh
#CMSSDT_DAS_CLIENT_SIGN:12345678901234567890ABCDEFABCDEF
#Do not change the above magic line. It is signature for the cmssw ibs das_cleint wrapper

QUERY=
FORMAT="plain"
HELP=
for ((i=1; i<=$#; i++)); do
  next=$((i+1))
  case  ${!i} in
    --query=*  ) QUERY=$(echo ${!i} | sed 's|.*=||') ;;
    --query    ) QUERY=${!next} ;;
    --format=* ) FORMAT=$(echo ${!i} | sed 's|.*=||') ;;
    --format   ) FORMAT=${!next} ;;
    -h|--help  ) HELP=YES ;;
  esac
done

ORIG_DAS_CLIENT=""
for DAS_CLIENT in $(echo $PATH | tr ':' '\n' | sed 's|$|/das_client|') ; do
 [ -e ${DAS_CLIENT} ] || continue
 if [ $(head -2 ${DAS_CLIENT} | grep 'CMSSDT_DAS_CLIENT_SIGN' | wc -l) -eq 0 ] ; then ORIG_DAS_CLIENT=${DAS_CLIENT}; break; fi
done

if [ "X${ORIG_DAS_CLIENT}" = "X" ] ; then
  echo "das_client: Command not found." 1>&2
  exit 1
fi

if [ "${QUERY}" = "" -o "${HELP}" != "" ] ; then
  ${ORIG_DAS_CLIENT} "$@"
  exit $?
fi

QUERY_SHA=$(echo -n "${QUERY}" | sha256sum | sed 's| .*$||;s| *||;s|^\(..\)|\1/\1|')
QUERY_URL="https://raw.githubusercontent.com/cms-sw/cms-sw.github.io/master/das_queries/${QUERY_SHA}"
DAS_QUERY_DIR=das_query/$$/${QUERY_SHA}
if [ "X${LOCALRT}" != "X" ] ; then DAS_QUERY_DIR="${LOCALRT}/${DAS_QUERY_DIR}" ; fi
mkdir -p ${DAS_QUERY_DIR}
echo "${QUERY}" > ${DAS_QUERY_DIR}.query
if [ "${FORMAT}" = "json" ]  ; then
  QUERY_RESULTS=$(curl -L -s "${QUERY_URL}.json" || true)
else
  QUERY_RESULTS=$((curl -L -s "${QUERY_URL}" || true) | grep /store/ | sed 's| ||g;s|"||g;s|,||g')
fi

if [ $(echo "${QUERY_RESULTS}" | grep '/store/' | wc -l) -gt 0 ] ; then
  echo "${QUERY_RESULTS}"
else
  ${ORIG_DAS_CLIENT} "$@"
fi
