#!/bin/bash -ex
THRESHOLD_TIME=""
[ "X$1" = "X" ] || THRESHOLD_TIME="--threshold $1"
EXTRA_OPTS="$2"
voms-proxy-init
WORKSPACE="${WORKSPACE-$PWD}"
JOBS=$(getconf _NPROCESSORS_ONLN)
USE_DASGO=$3
PUSH_RESULTS=$4
if [ "$USE_DASGO" = "true" ] ; then 
  USE_DASGO="-c dasgoclient"
else
  USE_DASGO=""
fi

CMS_BOT_DIR=$(dirname $0)
case $CMS_BOT_DIR in /*) ;; *) CMS_BOT_DIR=$(pwd)/${CMS_BOT_DIR} ;; esac

cd $WORKSPACE
if [ ! -d das_results ] ; then
  git clone git@github.com:cms-sw/cms-sw.github.io.git das_results
fi

rm -f $WORKSPACE/error
$CMS_BOT_DIR/das_cache.py ${EXTRA_OPTS} ${USE_DASGO} --jobs $JOBS ${THRESHOLD_TIME} --store $WORKSPACE/das_results/das_queries --query "$5" || touch $WORKSPACE/error
if [ "$PUSH_RESULTS" = "true" ] ; then
  pushd $WORKSPACE/das_results
  git add das_queries
  if [ $(git diff --name-only origin/master | wc -l) -gt 0 ] ; then
    git commit -a -m "Updated das queries"
    git pull --rebase
    git push origin
  fi
  popd
fi
if [ -e $WORKSPACE/error ] ; then
  exit 1
fi

