#!/bin/bash -ex
THRESHOLD_TIME=""
[ "X$1" = "X" ] || THRESHOLD_TIME="--threshold $1"
EXTRA_OPTS="$2"
voms-proxy-init
WORKSPACE="${WORKSPACE-$PWD}"

CMS_BOT_DIR=$(dirname $0)
case $CMS_BOT_DIR in /*) ;; *) CMS_BOT_DIR=$(pwd)/${CMS_BOT_DIR} ;; esac

cd $WORKSPACE
if [ ! -d das_results ] ; then
  git clone git@github.com:cms-sw/cms-sw.github.io.git das_results
fi

rm -f $WORKSPACE/error
$CMS_BOT_DIR/das_cache.py ${EXTRA_OPTS} --jobs 4 ${THRESHOLD_TIME} --store $WORKSPACE/das_results/das_queries || touch $WORKSPACE/error
pushd $WORKSPACE/das_results
  git add das_queries
  if [ $(git diff --name-only origin/master | wc -l) -gt 0 ] ; then
    git commit -a -m "Updated das queries"
    git pull --rebase
    git push origin
  fi
popd

if [ -e $WORKSPACE/error ] ; then
  exit 1
fi

