#!/bin/sh -ex
CMS_BOT_DIR=$(dirname $0)/..
source $CMS_BOT_DIR/cmsrep.sh
RELEASE_QUEUE=$1
ARCHITECTURE=$2
UPLOAD_ID=$3
PKGS="$4"
eval `cat $CMS_BOT_DIR/config.map | grep -v 'DISABLED=' | grep "SCRAM_ARCH=$ARCHITECTURE;" | grep "RELEASE_QUEUE=$RELEASE_QUEUE;"`
git clone --depth 1 git@github.com:cms-sw/cmsdist -b $CMSDIST_TAG
git clone --depth 1 git@github.com:cms-sw/pkgtools -b $PKGTOOLS_TAG
if [ "X$ENABLE_DEBUG" = X ]; then
  perl -p -i -e 's/^[\s]*%define[\s]+subpackageDebug[\s]+./#subpackage debug disabled/' cmsdist/cmssw.spec cmsdist/coral.spec cmsdist/root.spec
fi
RELEASE_NAME=${RELEASE_QUEUE}_2099-01-01-2400
perl -p -i -e "s/### RPM cms cmssw .*/### RPM cms cmssw ${RELEASE_NAME}/" cmsdist/cmssw.spec

PYTHONPATH= ./pkgtools/cmsBuild $(cmsbuild_args "${BUILD_OPTS}" "${MULTIARCH_OPTS}") --use-dev --repo cms --architecture $ARCHITECTURE --work-dir w --pretend build cmssw-patch cmssw-ib bootstrap-driver cms-common fwlite gcc-toolfile $PKGS
mkdir upload
used="upload/${RELEASE_QUEUE}-${ARCHITECTURE}.txt"
python3 -c "import json; print ('\n'.join(['${CMSDIST_TAG}:%s' % f for f in json.load(open('w/cmsdist_files.json')).keys()]))" | sort > $used
mv w/cmsdist_files.json upload/${RELEASE_QUEUE}-${ARCHITECTURE}.json
source $CMS_BOT_DIR/jenkins-artifacts
send_jenkins_artifacts $(/bin/pwd)/upload/ check-unused-cmsdist-packages/${UPLOAD_ID}/
