#!/bin/sh -ex
CMS_BOT_DIR=$(dirname $0)/..
RELEASE_QUEUE=$1
ARCHITECTURE=$2
UPLOAD_ID=$3
eval `cat $CMS_BOT_DIR/config.map | grep -v 'DISABLED=' | grep "SCRAM_ARCH=$ARCHITECTURE;" | grep "RELEASE_QUEUE=$RELEASE_QUEUE;"`
git clone --depth 1 git@github.com:cms-sw/cmsdist -b $CMSDIST_TAG
git clone --depth 1 git@github.com:cms-sw/pkgtools -b $PKGTOOLS_TAG
if [ "X$ENABLE_DEBUG" = X ]; then
  perl -p -i -e 's/^[\s]*%define[\s]+subpackageDebug[\s]+./#subpackage debug disabled/' cmsdist/cmssw.spec cmsdist/coral.spec cmsdist/root.spec
fi
perl -p -i -e "s/### RPM cms cmssw .*/### RPM cms cmssw ${RELEASE_QUEUE}_2099-01-01-2400/" cmsdist/cmssw.spec

PYTHONPATH= ./pkgtools/cmsBuild --use-dev --repo cms --architecture $ARCHITECTURE --work-dir w --pretend build cmssw bootstrap-bundle cms-common
used="$(/bin/pwd)/${RELEASE_QUEUE}-${ARCHITECTURE}.txt"
touch $used
for u in $(python -c "import json; print '\n'.join(json.load(open('w/cmsdist_files.json')).keys())" | sort | uniq) ; do
  echo "$CMSDIST_TAG:$u" >> $used
done
source $CMS_BOT_DIR/jenkins-artifacts
send_jenkins_artifacts $used check-unused-cmsdist-packages/${UPLOAD_ID}/$(basename $used)
