apiVersion: v1
kind: Pod
metadata:
  name: ngt-@SESSION_ID@
  labels:
    home-eos: "true"
    mount-cvmfs: "true"
    mount-afs: "false"
    mount-eos: "true"
spec:
  containers:
    - name: container
      image: cmssw/el9:x86_64
      command: ["/usr/bin/tini", "--"]
      args: ["sleep", "infinity"]
      env:
        - name: TZ
          value: Europe/Zurich
      resources:
        limits:
          @GPU_TYPE@.com/gpu: @GPU_COUNT@
  nodeSelector:
    @GPU_TYPE@.com/gpu.@PRODUCT@: @GPU@
