#!/bin/bash -ex
if [ "$HOST" = "" ] ; then
  if [ "$BUILD_CAUSE_UPSTREAMTRIGGER" = "true" -o "$ROOT_BUILD_CAUSE" = "MANUALTRIGGER" ] ; then
    JDATA="${JOB_NAME}:${BUILD_ID}"
    hname=$(hostname -f)
    JURL=$(echo $LOCAL_JENKINS_URL | sed "s|//localhost|//$hname|")
    echo "${JDATA}" > $WORKSPACE/../jenkins-wekhook.data
    uheader=$(grep '<forwardedUser>' $JENKINS_HOME/config.xml | sed 's|.*<forwardedUser> *||;s| *</forwardedUser>.*||')
    curl -s -k -f --retry 3 --retry-delay 5 --max-time 30 -X POST -d \
      "{\"DATA\":\"${JDATA}\",\"JENKINS_SERVER\":\"${JURL}\",\"JENKINS_USER\":\"cmssdt\",\"USER_HEADER\":\"${uheader}\"}" \
      --header 'Content-Type: application/json' \
      https://cmssdt.cern.ch/SDT/cgi-bin/jenkins_webhook > out.txt
    cat out.txt
    grep 'Unable to start jenkins job' out.txt >/dev/null && exit 1
    exit 0
  fi
fi
HOSTNAME=$(hostname -I)
IP_OK=false
for ip in $(hostname -I) ; do
  [ "$ip" != "${HOST}" ] || IP_OK=true
done
$IP_OK || exit 1
if [ -f $WORKSPACE/../jenkins-wekhook.data ] ; then
  ODATA=$(cat $WORKSPACE/../jenkins-wekhook.data)
  rm -f $WORKSPACE/../jenkins-wekhook.data
  if [ "${ODATA}" != "${DATA}" ] ; then
    exit 1
  fi
fi
